# Query
findGuestById:
  handler: dist/graphql/query.findGuestById
  environment:
    MYSQL_HOST: ${env:AURORA_HOST}
    DB_NAME: ${env:DB_NAME}
    USERNAME: ${env:USERNAME}
    PASSWORD: ${env:PASSWORD}

findHostById:
  handler: dist/graphql/query.findHostById
  environment:
    MYSQL_HOST: ${env:AURORA_HOST}
    DB_NAME: ${env:DB_NAME}
    USERNAME: ${env:USERNAME}
    PASSWORD: ${env:PASSWORD}

# Mutation
registerGuest:
  handler: dist/graphql/mutation.registerGuest
  environment:
    MYSQL_HOST: ${env:AURORA_HOST}
    DB_NAME: ${env:DB_NAME}
    USERNAME: ${env:USERNAME}
    PASSWORD: ${env:PASSWORD}

registerHost:
  handler: dist/graphql/mutation.registerHost
  environment:
    MYSQL_HOST: ${env:AURORA_HOST}
    DB_NAME: ${env:DB_NAME}
    USERNAME: ${env:USERNAME}
    PASSWORD: ${env:PASSWORD}

removeGuestById:
  handler: dist/graphql/mutation.removeGuestById
  environment:
    MYSQL_HOST: ${env:AURORA_HOST}
    DB_NAME: ${env:DB_NAME}
    USERNAME: ${env:USERNAME}
    PASSWORD: ${env:PASSWORD}

removeHostById:
  handler: dist/graphql/mutation.removeHostById
  environment:
    MYSQL_HOST: ${env:AURORA_HOST}
    DB_NAME: ${env:DB_NAME}
    USERNAME: ${env:USERNAME}
    PASSWORD: ${env:PASSWORD}
