- Effect: "Allow"
  Action:
    - "logs:CreateLogGroup"
    - "logs:CreateLogStream"
    - "logs:PutLogEvents"
    - "ec2:CreateNetworkInterface"
    - "ec2:DescribeNetworkInterfaces"
    - "ec2:DeleteNetworkInterface"
  Resource:
    - "*"
- Effect: "Allow"
  Action:
    - "ssm:GetParameter"
    - "ssm:GetParameters"
    - "ssm:GetParametersByPath"
    - "ssm:DescribeParameters"
    - "ssm:PutParameter"
  Resource:
    - "Fn::Join":
        - ":"
        - - "arn:aws:ssm"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "*"
- Effect: "Allow"
  Action:
    - "sqs:ReceiveMessage"
    - "sqs:DeleteMessage"
    - "sqs:GetQueueAttributes"
  Resource:
    - "Fn::Join":
        - ":"
        - - "arn:aws:sqs"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "*"
- Effect: "Allow"
  Action:
    - "ses:*"
  Resource:
    - "Fn::Join":
        - ":"
        - - "arn:aws:ses"
          - "*"
          - "*"
          - "identity/*"
- Effect: "Allow"
  Action:
    - "sns:CreateTopic"
    - "sns:Publish"
  Resource:
    - "Fn::Join":
        - ":"
        - - "arn:aws:sns"
          - Ref: "AWS::Region"
          - Ref: "AWS::AccountId"
          - "*"
- Effect: "Allow"
  Action:
    - "s3:*"
  Resource:
    Fn::Join:
      - ""
      - - "arn:aws:s3:::*"
