service: rental-storage-user
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  iamRoleStatements: ${file(./aws/IAMRole.yml)}

custom:
  namespace: rental-storage
  service: user
  AURORA_HOST:
    Fn::GetAtt: [AuroraRDSCluster, Endpoint.Address]
  DB_NAME: ${env:DB_NAME}
  DB_USERNAME: ${env:DB_USERNAME}
  DB_PASSWORD: ${env:DB_PASSWORD}

functions:
  - ${file(./aws/functions/appsync.yml)}
  - ${file(./aws/functions/sqs.yml)}

resources:
  Resources:
    AuroraRDSCluster: ${file(./aws/resources/db/AuroraRDSCluster.yml)}
    AuroraRDSInstance: ${file(./aws/resources/db/AuroraRDSInstance.yml)}
    SQSQueue: ${file(./aws/resources/sqs/SQSQueue.yml)}
    SNSSubscriptionBookingCreated: ${file(./aws/resources/sqs/SNSSubscriptionBookingCreated.yml)}
    SQSQueuePolicy: ${file(./aws/resources/sqs/SQSQueuePolicy.yml)}
