service: service-user
variablesResolutionMode: 20210326

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: go1.x
  stage: local
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: ${self:provider.stage}-${aws:accountId}-sls-user
  iam:
    role: ${ssm:/terraform/iam/lambda-role-arn}
  apiGateway:
    restApiId: ${ssm:/terraform/apigateway/rest-api-id}
    restApiRootResourceId: ${ssm:/terraform/apigateway/rest-api-root-resource-id}
  ecr:
    images:
      app:
        path: ./
  environment:
    SERVICE_API_ENDPOINT: ${self:custom.SERVICE_API_ENDPOINT}
    STAGE: ${self:provider.stage}
    ACCOUNT_ID: ${aws:accountId}
    DB_HOST: ${self:custom.DB_HOST}
    DB_NAME: ${self:custom.DB_NAME}
    DB_USERNAME: ${self:custom.DB_USERNAME}
    DB_PASSWORD: ${self:custom.DB_PASSWORD}
    DB_PORT: ${self:custom.DB_PORT}

custom:
  namespace: app
  service: user
  DB_NAME: ${ssm:/terraform/rds/user-db-name}
  DB_USERNAME: ${ssm:/terraform/rds/user-db-username}
  DB_PASSWORD: ${ssm:/terraform/rds/user-db-password}
  DB_HOST: ${ssm:/terraform/rds/user-db-host}
  DB_PORT: ${ssm:/terraform/rds/user-db-port}
  SERVICE_API_ENDPOINT:
    Fn::Join:
      - ""
      - - "https://"
        - ${self:provider.apiGateway.restApiId}
        - ".execute-api."
        - ${self:provider.region}
        - ".amazonaws.com/"
        - ${self:provider.stage}
  export-env:
    filename: .env
    overwrite: true

functions:
  - ${file(./aws/functions/apigateway.yml)}
  # - ${file(./aws/functions/stream.yml)}
