Type: AWS::RDS::DBSubnetGroup
Properties:
  DBSubnetGroupDescription: "RDS Subnet Group"
  SubnetIds:
    - !Ref PrivateSubnetA
    - !Ref PrivateSubnetB
  Tags:
    - Key: "Name"
      Value: ${self:custom.namespace}-private-subnet-group
