DependsOn: ServerlessVPC
Type: AWS::EC2::SecurityGroup
Properties:
  GroupDescription: Ingress for Redis Cluster
  VpcId:
    Ref: ServerlessVPC
  SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: "6379"
      ToPort: "6379"
      SourceSecurityGroupId:
        Ref: ServerlessSecurityGroup
