name: Python

inputs:
  environment:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  AWS_REGION:
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup dependencies
      uses: ./.github/actions/setup-deps

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: "npm"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Load lambda environment variables into .env
      run: npm run generate:env:dev
      shell: bash

    - name: Install global dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
      shell: bash

    - name: Test Image Service
      run: |
        cd packages/service-image
        make integration-test

    - name: Test Slack Service
      run: |
        cd packages/service-slack
        make integration-test
