Type: "AWS::SNS::Subscription"
DependsOn:
  - ListingSQSQueue
  - SNSTopicItemSaved
Properties:
  Protocol: sqs
  TopicArn:
    Fn::Join:
      - ":"
      - - "arn:aws:sns"
        - Ref: "AWS::Region"
        - Ref: "AWS::AccountId"
        - ${self:custom.namespace}-item-${self:provider.stage}-item-saved
  Endpoint:
    Fn::Join:
      - ":"
      - - "arn:aws:sqs"
        - Ref: "AWS::Region"
        - Ref: "AWS::AccountId"
        - ${self:custom.namespace}-listing-${self:provider.stage}-queue
