Type: AWS::SQS::QueuePolicy
Properties:
  Queues:
    - Ref: ListingSQSQueue
  PolicyDocument:
    Version: "2012-10-17"
    Statement:
      - Sid: "allow-sns-messages"
        Effect: Allow
        Principal: "*"
        Resource:
          Fn::GetAtt: [ListingSQSQueue, Arn]
        Action: "SQS:SendMessage"
        Condition:
          ArnEquals:
            "aws:SourceArn":
              - Fn::Join:
                  - ":"
                  - - "arn:aws:sns"
                    - Ref: "AWS::Region"
                    - Ref: "AWS::AccountId"
                    - "${self:custom.namespace}-item-${self:provider.stage}-item-saved"
