Type: "AWS::SQS::Queue"
DependsOn: ListingSQSDLQueue
Properties:
  QueueName: "${self:custom.namespace}-listing-${self:provider.stage}-queue"
  VisibilityTimeout: 930
  RedrivePolicy:
    deadLetterTargetArn:
      Fn::Join:
        - ":"
        - - "arn:aws:sqs"
          - ${aws:region}
          - ${aws:accountId}
          - "${self:custom.namespace}-listing-${self:provider.stage}-dead-letter-queue"
    maxReceiveCount: 3
