version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/packages/service-authentication"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/packages/service-authorizer"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/packages/service-booking"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/packages/service-space"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/packages/service-user"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    directory: "/packages/service-slack"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/packages/composition"
    schedule:
      interval: "monthly"
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "monthly"
  - package-ecosystem: "terraform"
    directory: "/terraform"
    schedule:
      interval: "monthly"
