services:
  infrastructure:
    path: infrastructure

  user:
    path: packages/service-user
    dependsOn:
      - infrastructure

  listing:
    path: packages/service-listing
    dependsOn:
      - infrastructure

  image:
    path: packages/service-image
    dependsOn:
      - infrastructure

  booking:
    path: packages/service-booking
    dependsOn:
      - infrastructure

  api:
    path: api
    dependsOn:
      - infrastructure
      - booking
      - image
      - listing
      - user
