## THIS IS ONLY FOR LOCAL USE. CANNOT BE USED ON THE CI PIPELINE.
services:
  image:
    path: packages/service-image
    config: serverless.yml

  booking:
    path: packages/service-booking
    config: serverless.yml

  authorizer:
    path: packages/service-authorizer
    config: serverless.yml

  # payment:
  #   path: packages/service-payment
  #   config: serverless.yml

  slack:
    path: packages/service-slack
    config: serverless.yml

  user:
    path: packages/service-user
    config: serverless.yml

  listing:
    path: packages/service-listing
    config: serverless.yml

  authentication:
    path: packages/service-authentication
    config: serverless.yml

  composition:
    path: packages/composition
    config: serverless.yml

  api-appsync:
    path: appsync
    config: serverless.yml
    dependsOn:
      - composition
      - booking
      - image
      - listing
      - user
      - authorizer
      # - payment
      - authentication
      - slack
