services:
  infrastructure:
    path: infrastructure

  user:
    path: packages/service-user
    dependsOn:
      - infrastructure

  listing:
    path: packages/service-listing
    dependsOn:
      - infrastructure

  image:
    path: packages/service-image
    dependsOn:
      - infrastructure

  booking:
    path: packages/service-booking
    dependsOn:
      - infrastructure

  authorizer:
    path: packages/service-authorizer
    dependsOn:
      - infrastructure

  authentication:
    path: packages/service-authentication
    dependsOn:
      - infrastructure

  payment:
    path: packages/service-payment
    dependsOn:
      - infrastructure

  slack:
    path: packages/service-slack
    dependsOn:
      - infrastructure

  api:
    path: api
    dependsOn:
      - infrastructure
      - booking
      - image
      - listing
      - user
      - authorizer
      - authentication
      - payment
      - slack
