services:
  infrastructure:
    path: infrastructure

  authorizer:
    path: packages/service-authorizer
    dependsOn:
      - infrastructure

  # authentication:
  #   path: packages/service-authentication
  #   dependsOn:
  #     - infrastructure

  # booking:
  #   path: packages/service-booking
  #   dependsOn:
  #     - infrastructure

  # image:
  #   path: packages/service-image
  #   dependsOn:
  #     - infrastructure

  # item:
  #   path: packages/service-item
  #   dependsOn:
  #     - infrastructure

  # listing:
  #   path: packages/service-listing
  #   dependsOn:
  #     - infrastructure

  user:
    path: packages/service-user
    dependsOn:
      - infrastructure

  session:
    path: packages/service-session
    dependsOn:
      - infrastructure

  # api:
  #   path: api
  #   dependsOn:
  #     - authorizer
  #     - authentication
  #     - booking
  #     - infrastructure
  #     - image
  #     - item
  #     - listing
  #     - session
  #     - user
