Resources:
  AuroraRDSCluster: ${file(./config/resources/db/AuroraRDSCluster.yml)}
  AuroraRDSInstance: ${file(./config/resources/db/AuroraRDSInstance.yml)}
  SNSSubscriptionBookingCreated: ${file(./config/resources/sqs/SNSSubscriptionBookingCreated.yml)}
  SQSQueue: ${file(./config/resources/sqs/SQSQueue.yml)}
  SQSQueuePolicy: ${file(./config/resources/sqs/SQSQueuePolicy.yml)}
