Type: "AWS::DynamoDB::Table"
Properties:
  BillingMode: PAY_PER_REQUEST
  TableName: ${self:custom.BOOKING_TABLE_NAME}-${self:provider.stage}
  KeySchema:
    - AttributeName: OwnerId
      KeyType: HASH # partition
    - AttributeName: ListingId
      KeyType: RANGE
  AttributeDefinitions:
    - AttributeName: OwnerId
      AttributeType: S
    - AttributeName: ListingId
      AttributeType: S
  StreamSpecification:
    StreamViewType: NEW_AND_OLD_IMAGES
