service: rental-storage-item
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  # iamRoleStatements: ${file(./aws/IAMRole.yml)}
  iam: # test
    role: !ImportValue ExportedLambdaRoleArn
  deploymentBucket:
    name: rental-storage-item-resources
  apiGateway:
    restApiId: !ImportValue ApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ApiGatewayRootResourceId

custom:
  namespace: rental-storage
  service: item
  DB_NAME: !ImportValue ExportedItemRDSDBName
  DB_USERNAME: !ImportValue ExportedItemRDSDBUsername
  DB_PASSWORD: !ImportValue ExportedItemRDSDBPassword
  DB_HOST: !ImportValue ExportedItemRDSDBHost
  SERVICE_API_ENDPOINT:
    Fn::Join:
      - ""
      - - "https://"
        - ${self:provider.apiGateway.restApiId}
        - ".execute-api."
        - ${self:provider.region}
        - ".amazonaws.com/"
        - ${self:provider.stage}

functions:
  - ${file(./aws/functions/apigateway.yml)}
  - ${file(./aws/functions/stream.yml)}
