# Query
findListingById:
  handler: dist/adapter/graphql/query/findListingById.handler
  name: ${self:custom.namespace}-${self:custom.service}-graphql-findListingById
  environment:
    MYSQL_HOST: ${self:custom.AURORA_HOST}
    DB_NAME: ${env:DB_NAME}
    USERNAME: ${env:DB_USERNAME}
    PASSWORD: ${env:DB_PASSWORD}

findListingsWithinLatLng:
  handler: dist/adapter/graphql/query/findListingsWithinLatLng.handler
  name: ${self:custom.namespace}-${self:custom.service}-graphql-findListingsWithinLatLng
  environment:
    MYSQL_HOST: ${self:custom.AURORA_HOST}
    DB_NAME: ${env:DB_NAME}
    USERNAME: ${env:DB_USERNAME}
    PASSWORD: ${env:DB_PASSWORD}

# Mutation
addListing:
  handler: dist/adapter/graphql/mutation/addListing.handler
  name: ${self:custom.namespace}-${self:custom.service}-graphql-addListing
  environment:
    MYSQL_HOST: ${self:custom.AURORA_HOST}
    DB_NAME: ${env:DB_NAME}
    USERNAME: ${env:DB_USERNAME}
    PASSWORD: ${env:DB_PASSWORD}

removeListingById:
  handler: dist/adapter/graphql/mutation/removeListingById.handler
  name: ${self:custom.namespace}-${self:custom.service}-graphql-removeListingById
  environment:
    MYSQL_HOST: ${self:custom.AURORA_HOST}
    DB_NAME: ${env:DB_NAME}
    USERNAME: ${env:DB_USERNAME}
    PASSWORD: ${env:DB_PASSWORD}

# # Consumer
# ## SQS
consumeBookingCreated:
  handler: dist/adapter/consumer/booking/bookingCreated.handler
  name: ${self:custom.namespace}-${self:custom.service}-consumer-bookingCreated
  events:
    - sqs:
        enabled: true
        arn:
          Fn::GetAtt:
            - SQSQueue
            - Arn
