Type: "AWS::SNS::Subscription"
DependsOn:
  - UserQueue
  - SNSTopicItemCreated
Properties:
  Protocol: sqs
  TopicArn:
    Fn::Join:
      - ":"
      - - "arn:aws:sns"
        - ${aws:region}
        - ${aws:accountId}
        - ${self:provider.stage}-${self:custom.namespace}-item-topic
  Endpoint:
    Fn::Join:
      - ":"
      - - "arn:aws:sqs"
        - ${aws:region}
        - ${aws:accountId}
        - ${self:provider.stage}-${self:custom.namespace}-user-queue
