Type: "AWS::SQS::Queue"
DependsOn: BookingDLQueue
Properties:
  QueueName: ${self:provider.stage}-${self:custom.namespace}-booking-queue
  VisibilityTimeout: 930
  RedrivePolicy:
    deadLetterTargetArn:
      Fn::Join:
        - ":"
        - - "arn:aws:sqs"
          - ${aws:region}
          - ${aws:accountId}
          - ${self:provider.stage}-${self:custom.namespace}-booking-dead-letter-queue
    maxReceiveCount: 3
