Type: AWS::SQS::QueuePolicy
Properties:
  Queues:
    - !Ref QueueBooking
  PolicyDocument:
    Version: "2012-10-17"
    Statement:
      - Sid: "allow-sns-messages"
        Effect: Allow
        Principal: "*"
        Resource: !GetAtt
          - QueueBooking
          - Arn
        Action: "SQS:SendMessage"
        Condition:
          ArnEquals:
            "aws:SourceArn":
              - Fn::Join:
                  - ":"
                  - - "arn:aws:sns"
                    - ${aws:region}
                    - ${aws:accountId}
                    - ${self:provider.stage}-${self:custom.namespace}-user-topic
              - Fn::Join:
                  - ":"
                  - - "arn:aws:sns"
                    - ${aws:region}
                    - ${aws:accountId}
                    - ${self:provider.stage}-${self:custom.namespace}-payment-topic
