service: rental-a-locker-api-apigateway
frameworkVersion: "3"

useDotenv: true

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'local'}

custom:
  namespace: rental-a-locker

resources:
  Resources:
    #ApiGateway
    ApiGatewayRestApi: ${file(./aws/apigateway/RestApi.yml)}

  Outputs: ${file(./aws/outputs.yml)}
