// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	customerror "github.com/kokiebisu/rental-storage/service-authentication/internal/error"
	mock "github.com/stretchr/testify/mock"
)

// Controller is an autogenerated mock type for the Controller type
type Controller struct {
	mock.Mock
}

// SignIn provides a mock function with given fields: req
func (_m *Controller) SignIn(req interface{}) (interface{}, *customerror.CustomError) {
	ret := _m.Called(req)

	var r0 interface{}
	var r1 *customerror.CustomError
	if rf, ok := ret.Get(0).(func(interface{}) (interface{}, *customerror.CustomError)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) *customerror.CustomError); ok {
		r1 = rf(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

// SignUp provides a mock function with given fields: req
func (_m *Controller) SignUp(req interface{}) (interface{}, *customerror.CustomError) {
	ret := _m.Called(req)

	var r0 interface{}
	var r1 *customerror.CustomError
	if rf, ok := ret.Get(0).(func(interface{}) (interface{}, *customerror.CustomError)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) *customerror.CustomError); ok {
		r1 = rf(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

// Verify provides a mock function with given fields: req
func (_m *Controller) Verify(req interface{}) (interface{}, *customerror.CustomError) {
	ret := _m.Called(req)

	var r0 interface{}
	var r1 *customerror.CustomError
	if rf, ok := ret.Get(0).(func(interface{}) (interface{}, *customerror.CustomError)); ok {
		return rf(req)
	}
	if rf, ok := ret.Get(0).(func(interface{}) interface{}); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) *customerror.CustomError); ok {
		r1 = rf(req)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*customerror.CustomError)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewController interface {
	mock.TestingT
	Cleanup(func())
}

// NewController creates a new instance of Controller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewController(t mockConstructorTestingTNewController) *Controller {
	mock := &Controller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
