// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	booking "github.com/kokiebisu/rental-storage/service-booking/internal/core/domain/booking"
	errors "github.com/kokiebisu/rental-storage/service-booking/internal/error"

	mock "github.com/stretchr/testify/mock"
)

// BookingService is an autogenerated mock type for the BookingService type
type BookingService struct {
	mock.Mock
}

// CreateBooking provides a mock function with given fields: id, userId, spaceId, imageUrls, description, startDate, endDate, createdAt, updatedAt
func (_m *BookingService) CreateBooking(id string, userId string, spaceId string, imageUrls []string, description string, startDate string, endDate string, createdAt string, updatedAt string) (string, *errors.CustomError) {
	ret := _m.Called(id, userId, spaceId, imageUrls, description, startDate, endDate, createdAt, updatedAt)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string, string, []string, string, string, string, string, string) string); ok {
		r0 = rf(id, userId, spaceId, imageUrls, description, startDate, endDate, createdAt, updatedAt)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 *errors.CustomError
	if rf, ok := ret.Get(1).(func(string, string, string, []string, string, string, string, string, string) *errors.CustomError); ok {
		r1 = rf(id, userId, spaceId, imageUrls, description, startDate, endDate, createdAt, updatedAt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.CustomError)
		}
	}

	return r0, r1
}

// FindById provides a mock function with given fields: uid
func (_m *BookingService) FindById(uid string) (booking.Entity, *errors.CustomError) {
	ret := _m.Called(uid)

	var r0 booking.Entity
	if rf, ok := ret.Get(0).(func(string) booking.Entity); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Get(0).(booking.Entity)
	}

	var r1 *errors.CustomError
	if rf, ok := ret.Get(1).(func(string) *errors.CustomError); ok {
		r1 = rf(uid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.CustomError)
		}
	}

	return r0, r1
}

// FindManyBySpaceId provides a mock function with given fields: spaceId
func (_m *BookingService) FindManyBySpaceId(spaceId string) ([]booking.Entity, *errors.CustomError) {
	ret := _m.Called(spaceId)

	var r0 []booking.Entity
	if rf, ok := ret.Get(0).(func(string) []booking.Entity); ok {
		r0 = rf(spaceId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]booking.Entity)
		}
	}

	var r1 *errors.CustomError
	if rf, ok := ret.Get(1).(func(string) *errors.CustomError); ok {
		r1 = rf(spaceId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.CustomError)
		}
	}

	return r0, r1
}

// FindUserBookings provides a mock function with given fields: userId
func (_m *BookingService) FindUserBookings(userId string) ([]booking.Entity, *errors.CustomError) {
	ret := _m.Called(userId)

	var r0 []booking.Entity
	if rf, ok := ret.Get(0).(func(string) []booking.Entity); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]booking.Entity)
		}
	}

	var r1 *errors.CustomError
	if rf, ok := ret.Get(1).(func(string) *errors.CustomError); ok {
		r1 = rf(userId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.CustomError)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewBookingService interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookingService creates a new instance of BookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookingService(t mockConstructorTestingTNewBookingService) *BookingService {
	mock := &BookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
