// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	booking "github.com/kokiebisu/rental-storage/service-booking/internal/core/domain/booking"
	errors "github.com/kokiebisu/rental-storage/service-booking/internal/error"

	mock "github.com/stretchr/testify/mock"
)

// BookingService is an autogenerated mock type for the BookingService type
type BookingService struct {
	mock.Mock
}

// AcceptBooking provides a mock function with given fields: uid
func (_m *BookingService) AcceptBooking(uid string) (booking.Entity, *errors.CustomError) {
	ret := _m.Called(uid)

	var r0 booking.Entity
	var r1 *errors.CustomError
	if rf, ok := ret.Get(0).(func(string) (booking.Entity, *errors.CustomError)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(string) booking.Entity); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Get(0).(booking.Entity)
	}

	if rf, ok := ret.Get(1).(func(string) *errors.CustomError); ok {
		r1 = rf(uid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.CustomError)
		}
	}

	return r0, r1
}

// CreateBooking provides a mock function with given fields: id, userId, spaceId, imageUrls, bookingStatus, description, startDate, endDate, createdAt, updatedAt
func (_m *BookingService) CreateBooking(id string, userId string, spaceId string, imageUrls []string, bookingStatus string, description string, startDate string, endDate string, createdAt string, updatedAt string) (string, *errors.CustomError) {
	ret := _m.Called(id, userId, spaceId, imageUrls, bookingStatus, description, startDate, endDate, createdAt, updatedAt)

	var r0 string
	var r1 *errors.CustomError
	if rf, ok := ret.Get(0).(func(string, string, string, []string, string, string, string, string, string, string) (string, *errors.CustomError)); ok {
		return rf(id, userId, spaceId, imageUrls, bookingStatus, description, startDate, endDate, createdAt, updatedAt)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, []string, string, string, string, string, string, string) string); ok {
		r0 = rf(id, userId, spaceId, imageUrls, bookingStatus, description, startDate, endDate, createdAt, updatedAt)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, string, string, []string, string, string, string, string, string, string) *errors.CustomError); ok {
		r1 = rf(id, userId, spaceId, imageUrls, bookingStatus, description, startDate, endDate, createdAt, updatedAt)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.CustomError)
		}
	}

	return r0, r1
}

// FindBookingById provides a mock function with given fields: uid
func (_m *BookingService) FindBookingById(uid string) (booking.Entity, *errors.CustomError) {
	ret := _m.Called(uid)

	var r0 booking.Entity
	var r1 *errors.CustomError
	if rf, ok := ret.Get(0).(func(string) (booking.Entity, *errors.CustomError)); ok {
		return rf(uid)
	}
	if rf, ok := ret.Get(0).(func(string) booking.Entity); ok {
		r0 = rf(uid)
	} else {
		r0 = ret.Get(0).(booking.Entity)
	}

	if rf, ok := ret.Get(1).(func(string) *errors.CustomError); ok {
		r1 = rf(uid)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.CustomError)
		}
	}

	return r0, r1
}

// FindBookingsBySpaceId provides a mock function with given fields: spaceId, bookingStatus
func (_m *BookingService) FindBookingsBySpaceId(spaceId string, bookingStatus string) ([]booking.Entity, *errors.CustomError) {
	ret := _m.Called(spaceId, bookingStatus)

	var r0 []booking.Entity
	var r1 *errors.CustomError
	if rf, ok := ret.Get(0).(func(string, string) ([]booking.Entity, *errors.CustomError)); ok {
		return rf(spaceId, bookingStatus)
	}
	if rf, ok := ret.Get(0).(func(string, string) []booking.Entity); ok {
		r0 = rf(spaceId, bookingStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]booking.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) *errors.CustomError); ok {
		r1 = rf(spaceId, bookingStatus)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.CustomError)
		}
	}

	return r0, r1
}

// FindBookingsByUserId provides a mock function with given fields: userId, bookingStatus
func (_m *BookingService) FindBookingsByUserId(userId string, bookingStatus string) ([]booking.Entity, *errors.CustomError) {
	ret := _m.Called(userId, bookingStatus)

	var r0 []booking.Entity
	var r1 *errors.CustomError
	if rf, ok := ret.Get(0).(func(string, string) ([]booking.Entity, *errors.CustomError)); ok {
		return rf(userId, bookingStatus)
	}
	if rf, ok := ret.Get(0).(func(string, string) []booking.Entity); ok {
		r0 = rf(userId, bookingStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]booking.Entity)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) *errors.CustomError); ok {
		r1 = rf(userId, bookingStatus)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errors.CustomError)
		}
	}

	return r0, r1
}

type mockConstructorTestingTNewBookingService interface {
	mock.TestingT
	Cleanup(func())
}

// NewBookingService creates a new instance of BookingService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewBookingService(t mockConstructorTestingTNewBookingService) *BookingService {
	mock := &BookingService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
