Type: AWS::S3::Bucket
Properties:
  BucketName: ${self:provider.stage}-${self:custom.namespace}-listing-profile
  AccessControl: PublicReadWrite
  CorsConfiguration:
    CorsRules:
      - AllowedMethods:
        - GET
        - PUT
        - POST
        - HEAD
        AllowedOrigins:
        - "*"
        AllowedHeaders:
        - "*"