service: service-slack
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: python3.8
  stage: local
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-${aws:accountId}-sls-slack
  iam:
    role: ${ssm:/terraform/iam/lambda-role-arn}
  ecr:
    images:
      app:
        path: ./
        file: Dockerfile
        buildArgs:
  environment:
    ENV: local
    ACCOUNT_ID: ${aws:accountId}
    STAGE: ${self:provider.stage}

custom:
  namespace: app
  service: slack
  export-env:
    filename: .env
    overwrite: true

functions:
  - ${file(./aws/functions/kinesis.yml)}
