USER_DB_NAME: user
USER_DB_USERNAME: master
USER_DB_PASSWORD: password
USER_DB_AURORA:
  HOST:
    Fn::GetAtt: [UserDBAuroraRDSCluster, Endpoint.Address]
  PORT:
    Fn::GetAtt: [UserDBAuroraRDSCluster, Endpoint.Port]
  VPC_CIDR: 10

LISTING_DB_NAME: listing
LISTING_DB_USERNAME: master
LISTING_DB_PASSWORD: password
LISTING_DB_AURORA:
  HOST:
    Fn::GetAtt: [ListingDBAuroraRDSCluster, Endpoint.Address]
  PORT:
    Fn::GetAtt: [ListingDBAuroraRDSCluster, Endpoint.Port]
  VPC_CIDR: 10
appSync:
  name: rental-storage-appsync
  authenticationType: API_KEY
