DependsOn: VPC
Type: AWS::EC2::SecurityGroup
Properties:
  GroupDescription: Ingress for Redis Cluster
  VpcId: !Ref VPC
  SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: "6379"
      ToPort: "6379"
      # CidrBlock: "0.0.0.0/0"
      SourceSecurityGroupId: !Ref LambdaSecurityGroup
  Tags:
    - Key: "Name"
      Value: ${self:custom.namespace}-cache-security-group
