DependsOn: VPC
Type: AWS::EC2::SecurityGroup
Properties:
  GroupDescription: SecurityGroup for Lambda Functions
  VpcId: !Ref VPC
  SecurityGroupIngress:
    - IpProtocol: tcp
      FromPort: 6379
      ToPort: 6379
      CidrIp: "0.0.0.0/0"
  Tags:
    - Key: "Name"
      Value: ${self:custom.namespace}-lambda-security-group
