DependsOn: VPC
Type: AWS::EC2::SecurityGroup
Properties:
  GroupDescription: SecurityGroup for Serverless Functions
  VpcId: !Ref VPC
  Tags:
    - Key: "Name"
      Value: ${self:custom.namespace}-serverles-security-group
