DependsOn: ServerlessStorageSecurityGroup
Type: AWS::ElastiCache::CacheCluster
Properties:
  AutoMinorVersionUpgrade: true
  Engine: redis
  CacheNodeType: cache.t2.micro
  NumCacheNodes: 1
  VpcSecurityGroupIds:
    - !GetAtt ServerlessStorageSecurityGroup.GroupId
  CacheSubnetGroupName: !Ref CacheSubnetGroup
