service: rental-storage-booking
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  iam:
    role: !ImportValue ExportedLambdaRoleArn
  deploymentBucket:
    name: rental-storage-booking-resources
  apiGateway:
    restApiId: !ImportValue ApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ApiGatewayRootResourceId

custom:
  namespace: rental-storage
  service: booking
  TABLE_NAME: !ImportValue ExportedBookingDynamoDBTableName

functions:
  - ${file(./aws/functions/apigateway.yml)}
  - ${file(./aws/functions/appsync.yml)}
