service: service-booking
variablesResolutionMode: 20210326

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: go1.x
  stage: local
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: ${self:provider.stage}-${aws:accountId}-sls-booking
  iam:
    role: ${ssm:/terraform/iam/lambda-role-arn}
  apiGateway:
    restApiId: ${ssm:/terraform/apigateway/rest-api-id}
    restApiRootResourceId: ${ssm:/terraform/apigateway/rest-api-root-resource-id}
  ecr:
    images:
      app:
        path: ./
        file: Dockerfile
        buildArgs:
  environment:
    ENV: local
    SERVICE_API_ENDPOINT: ${self:custom.SERVICE_API_ENDPOINT}
    TABLE_NAME: ${self:custom.TABLE_NAME}
    ACCOUNT_ID: ${aws:accountId}
    namespace: ${self:custom.namespace}
    service: ${self:custom.service}
    STAGE: ${self:provider.stage}

custom:
  namespace: app
  service: booking
  TABLE_NAME: ${ssm:/terraform/dynamodb/booking-table-name}
  SERVICE_API_ENDPOINT:
    Fn::Join:
      - ""
      - - "https://"
        - ${self:provider.apiGateway.restApiId}
        - ".execute-api."
        - ${self:provider.region}
        - ".amazonaws.com/"
        - ${self:provider.stage}
  export-env:
    filename: .env
    overwrite: true

functions:
  - ${file(./aws/functions/apigateway.yml)}
