service: rental-a-locker-authentication
frameworkVersion: "3"

plugins:
  - serverless-export-env

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  iam:
    role: !ImportValue ExportedRoleLambdaArn
  apiGateway:
    restApiId: !ImportValue ApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ApiGatewayRootResourceId
  environment:
    SERVICE_API_ENDPOINT: ${self:custom.SERVICE_API_ENDPOINT}
    ACCOUNT_ID: ${aws:accountId}

custom:
  namespace: rental-a-locker
  service: authentication
  SERVICE_API_ENDPOINT:
    Fn::Join:
      - ""
      - - "https://"
        - ${self:provider.apiGateway.restApiId}
        - ".execute-api."
        - ${self:provider.region}
        - ".amazonaws.com/"
        - ${self:provider.stage}
  export-env:
    filename: .env
    overwrite: true

functions:
  - ${file(./aws/functions/apigateway.yml)}
