service: rental-a-locker-authentication
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket
  - serverless-export-env

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: rental-a-locker-authentication-resources
  iam:
    role: !ImportValue ${self.provider.stage}-ExportedRoleLambdaArn
  apiGateway:
    restApiId: !ImportValue ${self.provider.stage}-ApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self.provider.stage}-ApiGatewayRootResourceId

custom:
  namespace: rental-a-locker
  service: authentication
  SERVICE_API_ENDPOINT:
    Fn::Join:
      - ""
      - - "https://"
        - ${self:provider.apiGateway.restApiId}
        - ".execute-api."
        - ${self:provider.region}
        - ".amazonaws.com/"
        - ${self:provider.stage}

functions:
  - ${file(./aws/functions/apigateway.yml)}
