# Query
- type: AWS_LAMBDA
  name: findListingByIdFunction
  config:
    functionName: findListingById

- type: AWS_LAMBDA
  name: findListingsWithinLatLngFunction
  config:
    functionName: findListingsWithinLatLng

# Mutation
- type: AWS_LAMBDA
  name: addListingFunction
  config:
    functionName: addListing

- type: AWS_LAMBDA
  name: removeListingByIdFunction
  config:
    functionName: removeListingById
