name: Typescript

inputs:
  package:
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Install node_modules
      run: |
        cd packages/service-${{ inputs.package }}
        npm install
      shell: bash

    - name: Build
      run: |
        cd packages/service-${{ inputs.package }}
        npm run build
      shell: bash

    - uses: actions/upload-artifact@v2
      rentention-period: 1
      with:
        name: dist-${{ matrix.package }}-${{ github.sha }}
        path: packages/service-${{ inputs.package }}/dist
