name: Typescript

inputs:
  package:
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Retrieve node modules cache
      id: node-modules-cache
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: node-modules-cache

    # - name: Install node_modules
    #   run: make install-deps
    #   if: steps.node-modules-cache.outputs.cache-hit != 'true'
    #   shell: bash

    - name: Install node_modules
      run: |
        cd packages/service-${{ inputs.package }}
        npm install
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      shell: bash

    # - name: Build
    #   run: npm run build
    #   shell: bash

    - name: Retrieve dist modules cache
      id: dist-cache
      uses: actions/cache@v3
      with:
        path: "packages/service-${{ matrix.package }}/dist"
        key: dist-cache

    - name: Build
      run: |
        cd packages/service-${{ inputs.package }}
        npm run build
      shell: bash
