Type: "AWS::SQS::Queue"
Properties:
  QueueName: "${self:custom.namespace}-${self:custom.service}-${self:provider.stage}-queue"
  VisibilityTimeout: 930
  # RedrivePolicy:
  #   deadLetterTargetArn:
  #     Fn::Join:
  #       - ":"
  #       - - "arn:aws:sqs"
  #         - Ref: "AWS::Region"
  #         - Ref: "AWS::AccountId"
  #         - "${self:custom.namespace}-${self:custom.service}-dead-letter-queue"
  #   maxReceiveCount: 3
