name: Dependency Setup

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: "npm"

    - name: Retreive node_modules cache
      id: node-modules-cache
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: node-modules-cache

    - name: Install root dependencies
      run: npm install
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      shell: bash

    - name: Install package dependencies
      run: make install-deps
      if: steps.node-modules-cache.outputs.cache-hit != 'true'
      shell: bash

    - name: Cache node modules
      id: node-modules-cache
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: node-modules-cache
