service: rental-storage-listing
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

custom:
  namespace: rental-storage
  service: listing
  AURORA_HOST:
    Fn::GetAtt: [AuroraRDSCluster, Endpoint.Address]

functions:
  - ${file(./aws/functions/appsync.yml)}
  - ${file(./aws/functions/sqs.yml)}

resources:
  Resources:
    AuroraRDSCluster: ${file(./aws/resources/db/AuroraRDSCluster.yml)}
    AuroraRDSInstance: ${file(./aws/resources/db/AuroraRDSInstance.yml)}
    SNSSubscriptionBookingCreated: ${file(./aws/resources/sqs/SNSSubscriptionBookingCreated.yml)}
    SQSQueue: ${file(./aws/resources/sqs/SQSQueue.yml)}
    SQSQueuePolicy: ${file(./aws/resources/sqs/SQSQueuePolicy.yml)}
