service: rental-a-locker-listing
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: rental-a-locker-listing-resources
  iam:
    role: !ImportValue ExportedRoleLambdaArn
  apiGateway:
    restApiId: !ImportValue ApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ApiGatewayRootResourceId

custom:
  namespace: rental-a-locker
  service: listing
  DB_NAME: !ImportValue ExportedListingRDSDBName
  DB_USERNAME: !ImportValue ExportedListingRDSDBUsername
  DB_PASSWORD: !ImportValue ExportedListingRDSDBPassword
  DB_HOST: !ImportValue ExportedListingRDSDBHost
  DB_PORT: !ImportValue ExportedListingRDSDBPort
  SERVICE_API_ENDPOINT:
    Fn::Join:
      - ""
      - - "https://"
        - ${self:provider.apiGateway.restApiId}
        - ".execute-api."
        - ${self:provider.region}
        - ".amazonaws.com/"
        - ${self:provider.stage}

functions:
  - ${file(./aws/functions/apigateway.yml)}
  - ${file(./aws/functions/appsync.yml)}
