service: rental-a-locker-listing
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket
  - serverless-export-env

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: rental-a-locker-listing-resources
  iam:
    role: !ImportValue ${self.provider.stage}-ExportedRoleLambdaArn
  apiGateway:
    restApiId: !ImportValue ${self.provider.stage}-ApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self.provider.stage}-ApiGatewayRootResourceId

custom:
  namespace: rental-a-locker
  service: listing
  DB_NAME: !ImportValue ${self.provider.stage}-ExportedListingRDSDBName
  DB_USERNAME: !ImportValue ${self.provider.stage}-ExportedListingRDSDBUsername
  DB_PASSWORD: !ImportValue ${self.provider.stage}-ExportedListingRDSDBPassword
  DB_HOST: !ImportValue ${self.provider.stage}-ExportedListingRDSDBHost
  DB_PORT: !ImportValue ${self.provider.stage}-ExportedListingRDSDBPort
  SERVICE_API_ENDPOINT:
    Fn::Join:
      - ""
      - - "https://"
        - ${self:provider.apiGateway.restApiId}
        - ".execute-api."
        - ${self:provider.region}
        - ".amazonaws.com/"
        - ${self:provider.stage}

functions:
  - ${file(./aws/functions/apigateway.yml)}
  - ${file(./aws/functions/appsync.yml)}
