service: rental-storage-session
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: rental-storage-session-resources

custom:
  namespace: rental-storage
  service: session

functions:
  - ${file(./aws/functions/appsync.yml)}
