name: Go

inputs:
  package:
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build ${{ inputs.package }} service
      run: |
        cd packages/service-${{ inputs.package }}
        make build
      shell: bash

    - name: Cache bin modules
      id: ${{ inputs.package }}-bin-cache
      uses: actions/cache@v3
      with:
        path: "**/bin"
        key: ${{ inputs.package }}-bin-cache
