name: Go

inputs:
  package:
    type: string

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Build ${{ inputs.package }} service
      run: |
        cd packages/service-${{ inputs.package }}
        make build
      shell: bash

    - uses: actions/upload-artifact@v3
      with:
        name: bin-${{ inputs.package }}-${{ github.sha }}
        path: packages/service-${{ inputs.package }}/bin
        retention-days: 1
