makeBooking:
  handler: dist/adapter/graphql/mutation.makeBooking
  name: ${self:custom.namespace}-${self:custom.service}-graphql-makeBooking
  environment:
    TABLE_NAME: !Ref BookingTable
    namespace: ${self:custom.namespace}
    service: ${self:custom.service}
    stage: ${self:provider.stage}
    account_id: 474489807730
# getTodos:
#   handler: dist/getTodos.handler
#   environment:
#     TODO_TABLE_NAME: !Ref TodoTable
# createTodo:
#   handler: dist/createTodo.handler
#   environment:
#     TODO_TABLE_NAME: !Ref TodoTable

# updateTodo:
#   handler: dist/updateTodo.handler
#   environment:
#     TODO_TABLE_NAME: !Ref TodoTable

# deleteTodo:
#   handler: dist/deleteTodo.handler
#   environment:
#     TODO_TABLE_NAME: !Ref TodoTable

# findAllCreatedBookings:
#   handler: dist/graphql/query.findAllCreatedBookings
#   environment:
#     TABLE_NAME: !Ref BookingTable
