// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	errors "github.com/kokiebisu/rental-storage/service-user/internal/error"
	mock "github.com/stretchr/testify/mock"

	user "github.com/kokiebisu/rental-storage/service-user/internal/core/domain/user"
)

// EventSender is an autogenerated mock type for the EventSender type
type EventSender struct {
	mock.Mock
}

// UserCreated provides a mock function with given fields: u
func (_m *EventSender) UserCreated(u user.DTO) *errors.CustomError {
	ret := _m.Called(u)

	var r0 *errors.CustomError
	if rf, ok := ret.Get(0).(func(user.DTO) *errors.CustomError); ok {
		r0 = rf(u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.CustomError)
		}
	}

	return r0
}

type mockConstructorTestingTNewEventSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewEventSender creates a new instance of EventSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEventSender(t mockConstructorTestingTNewEventSender) *EventSender {
	mock := &EventSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
