// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	errors "github.com/kokiebisu/rental-storage/service-user/internal/error"
	mock "github.com/stretchr/testify/mock"

	user "github.com/kokiebisu/rental-storage/service-user/internal/core/domain/user"
)

// UserPublisher is an autogenerated mock type for the UserPublisher type
type UserPublisher struct {
	mock.Mock
}

// UserCreated provides a mock function with given fields: u
func (_m *UserPublisher) UserCreated(u user.DTO) *errors.CustomError {
	ret := _m.Called(u)

	var r0 *errors.CustomError
	if rf, ok := ret.Get(0).(func(user.DTO) *errors.CustomError); ok {
		r0 = rf(u)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*errors.CustomError)
		}
	}

	return r0
}

type mockConstructorTestingTNewUserPublisher interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserPublisher creates a new instance of UserPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserPublisher(t mockConstructorTestingTNewUserPublisher) *UserPublisher {
	mock := &UserPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
