service: rental-a-locker-image
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'local'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: rental-a-locker-image-resources
  iam:
    role: !ImportValue ExportedRoleLambdaArn
  ecr:
    images:
      app:
        path: ./

custom:
  namespace: rental-a-locker
  service: image

functions:
  - ${file(./aws/functions/appsync.yml)}
