service: service-image
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: python3.9
  stage: local
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-${aws:accountId}-sls-image
  iam:
    role: ${ssm:/terraform/iam/service-lambda-role-arn}
  apiGateway:
    restApiId: ${ssm:/terraform/apigateway/rest-api-id}
    restApiRootResourceId: ${ssm:/terraform/apigateway/rest-api-root-resource-id}
  ecr:
    images:
      app:
        path: ./
        file: Dockerfile
        buildArgs:
  environment:
    STAGE: ${self:provider.stage}
    ACCOUNT_ID: ${aws:accountId}

custom:
  namespace: app
  service: image

functions:
  - ${file(./aws/functions/apigateway.yml)}
