service: rental-storage-image
frameworkVersion: "3"

# useDotenv: true

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221

custom:
  namespace: rental-storage
  service: image

functions:
  - ${file(./aws/functions/appsync.yml)}
