service: rental-a-locker-image
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: rental-a-locker-image-resources
  iam:
    role: !ImportValue ExportedRoleLambdaArn
  # ecr:
  #   images:
  #     app:
  #       path: ./

custom:
  namespace: rental-a-locker
  service: image

functions:
  - ${file(./aws/functions/appsync.yml)}
