service: rent-a-locker-image
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: rent-a-locker-image-resources

custom:
  namespace: rent-a-locker
  service: image

functions:
  - ${file(./aws/functions/appsync.yml)}
