USER_DB_DB_NAME: users
USER_DB_USERNAME: master
USER_DB_PASSWORD: password
USER_DB_AURORA:
  HOST:
    Fn::GetAtt: [AuroraRDSCluster, Endpoint.Address]
  PORT:
    Fn::GetAtt: [AuroraRDSCluster, Endpoint.Port]
  VPC_CIDR: 10
appSync:
  name: rental-storage-appsync
  authenticationType: API_KEY
