- type: AWS_LAMBDA
  name: createTodoFunction
  config:
    functionName: createTodo

- type: AWS_LAMBDA
  name: updateTodoFunction
  config:
    functionName: updateTodo

- type: AWS_LAMBDA
  name: deleteTodoFunction
  config:
    functionName: deleteTodo

- type: AWS_LAMBDA
  name: getTodosFunction
  config:
    functionName: getTodos
