service: rent-a-locker-authorizer
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: go1.x
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  iam:
    role: !ImportValue ExportedLambdaRoleArn
  deploymentBucket:
    name: rent-a-locker-authorizer-resources

custom:
  namespace: rent-a-locker
  service: authorizer

functions:
  Authorize:
    handler: bin/authorize
    name: ${self:custom.namespace}-${self:custom.service}-${self:provider.stage}-Authorizer
    package:
      include:
        - ./bin/authorize
