service: rental-a-locker-authorizer
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  iam:
    role: !ImportValue ExportedRoleLambdaArn
  deploymentBucket:
    name: rental-a-locker-authorizer-resources
  apiGateway:
    restApiId: !ImportValue ApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ApiGatewayRootResourceId

custom:
  namespace: rental-a-locker
  service: authorizer
  SERVICE_API_ENDPOINT:
    Fn::Join:
      - ""
      - - "https://"
        - ${self:provider.apiGateway.restApiId}
        - ".execute-api."
        - ${self:provider.region}
        - ".amazonaws.com/"
        - ${self:provider.stage}

functions:
  Authorize:
    handler: bin/authorize
    name: ${self:provider.stage}-${self:custom.namespace}-${self:custom.service}
    package:
      include:
        - ./bin/authorize
    environment:
      SERVICE_API_ENDPOINT: ${self:custom.SERVICE_API_ENDPOINT}
