service: rental-storage-authorizer
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: rental-storage-image-resources

custom:
  namespace: rental-storage
  service: authorizer

functions:
  GetPresignedURLGraphql:
    handler: authorizer.handler
    name: ${self:custom.namespace}-${self:custom.service}-${self:provider.stage}-Authorizer
