service: rental-a-locker-authorizer
variablesResolutionMode: 20210326

plugins:
  - serverless-deployment-bucket
  - serverless-export-env

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: ${self:provider.stage}-${aws:accountId}-rental-a-locker-authorizer-resources
  iam:
    role: !ImportValue ExportedRoleLambdaArn
  apiGateway:
    restApiId: !ImportValue ApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ApiGatewayRootResourceId
  ecr:
    images:
      app:
        path: ./
  environment:
    SERVICE_API_ENDPOINT: ${self:custom.SERVICE_API_ENDPOINT}

custom:
  namespace: app
  service: authorizer
  SERVICE_API_ENDPOINT:
    Fn::Join:
      - ""
      - - "https://"
        - ${self:provider.apiGateway.restApiId}
        - ".execute-api."
        - ${self:provider.region}
        - ".amazonaws.com/"
        - ${self:provider.stage}
  export-env:
    filename: .env
    overwrite: true

functions:
  Authorize:
    handler: bin/authorize
    name: ${self:provider.stage}-${self:custom.namespace}-${self:custom.service}
    package:
      include:
        - ./bin/authorize
    environment:
      SERVICE_API_ENDPOINT: ${self:custom.SERVICE_API_ENDPOINT}
