TODO_TABLE: todo-table
appSync:
  name: rental-storage-appsync
  authenticationType: API_KEY
  mappingTemplates: ${file(./config/appsync/mapping-templates.yml)}
  dataSources: ${file(./config/appsync/data-sources.yml)}
