TODO_TABLE: todo-table
appSync:
  name: rental-storage-appsync
  authenticationType: API_KEY
  mappingTemplates: ${file(./config/appsync/mapping-templates.yml)}
  dataSources: ${file(./config/appsync/data-sources.yml)}
DB_NAME: users
USERNAME: master
PASSWORD: password
AURORA:
  HOST:
    Fn::GetAtt: [AuroraRDSCluster, Endpoint.Address]
  PORT:
    Fn::GetAtt: [AuroraRDSCluster, Endpoint.Port]
  VPC_CIDR: 10
