getTodos:
  handler: functions/getTodos.handler
  environment:
    TODO_TABLE_NAME: !Ref TodoTable

createTodo:
  handler: functions/createTodo.handler
  environment:
    TODO_TABLE_NAME: !Ref TodoTable

updateTodo:
  handler: functions/updateTodo.handler
  environment:
    TODO_TABLE_NAME: !Ref TodoTable

deleteTodo:
  handler: functions/deleteTodo.handler
  environment:
    TODO_TABLE_NAME: !Ref TodoTable

getUser:
  handler: functions/getUser.handler
  environment:
    MYSQL_HOST: rental-storage-dev-aurorardscluster-yol3zzosiggj.cluster-clpv3k28jr2b.us-east-1.rds.amazonaws.com
    DB_NAME: users
    USERNAME: master
    PASSWORD: password

createUser:
  handler: functions/createUser.handler
  environment:
    MYSQL_HOST: rental-storage-dev-aurorardscluster-yol3zzosiggj.cluster-clpv3k28jr2b.us-east-1.rds.amazonaws.com
    DB_NAME: users
    USERNAME: master
    PASSWORD: password
