name: aws
runtime: nodejs14.x
stage: dev
region: us-east-1
lambdaHashingVersion: 20201221
iam:
  role: IAMRole
environment:
  #aurora
  AURORA_HOST: ${self:custom.AURORA.HOST}
  AURORA_PORT: ${self:custom.AURORA.PORT}
