# DependsOn: [!ImportValue ExportedServerlessVPCGA]
Type: AWS::RDS::DBInstance
Properties:
  DBInstanceClass: db.t2.small
  DBSubnetGroupName: !ImportValue ExportedServerlessSubnetGroup
  Engine: aurora
  EngineVersion: "5.6"
  PubliclyAccessible: true
  DBParameterGroupName: !ImportValue ExportedAuroraRDSInstanceParameter
  DBClusterIdentifier:
    Ref: AuroraRDSCluster
