name: Typescript

inputs:
  environment:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  AWS_REGION:
    required: true

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: "npm"

    - name: Retrieve cache
      uses: ./.github/actions/retrieve-cache

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1-node16
      with:
        aws-access-key-id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Cat Export
      run: cd packages/service-listing && echo "$(cat .env)"
      shell: bash

    - name: Test
      run: npm run test:integration
      shell: bash
