version: "3"

services:
  postgres:
    image: postgres:12.6-alpine
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: space_db
    ports:
      - "5432:5432"
