Type: "AWS::SNS::Subscription"
DependsOn:
  - UserSQSQueue
  - SNSTopicItemCreated
Properties:
  Protocol: sqs
  TopicArn:
    Fn::Join:
      - ":"
      - - "arn:aws:sns"
        - ${aws:region}
        - ${aws:accountId}
        - ${self:custom.namespace}-item-${self:provider.stage}-ItemCreated
  Endpoint:
    Fn::Join:
      - ":"
      - - "arn:aws:sqs"
        - ${aws:region}
        - ${aws:accountId}
        - ${self:custom.namespace}-user-${self:provider.stage}-queue
