Resources:
  # Infrastructure
  ServerlessInternetGateway: ${file(./config/resources/network/ServerlessInternetGateway.yml)}
  ServerlessVPC: ${file(./config/resources/network/ServerlessVPC.yml)}
  ServerlessVPCGA: ${file(./config/resources/network/ServerlessVPCGA.yml)}
  ServerlessSubnetA: ${file(./config/resources/network/ServerlessSubnetA.yml)}
  ServerlessSubnetB: ${file(./config/resources/network/ServerlessSubnetB.yml)}
  ServerlessSubnetC: ${file(./config/resources/network/ServerlessSubnetC.yml)}
  ServerlessSubnetGroup: ${file(./config/resources/network/ServerlessSubnetGroup.yml)}
  ServerlessSecurityGroup: ${file(./config/resources/network/ServerlessSecurityGroup.yml)}
  RouteTablePublic: ${file(./config/resources/network/RouteTablePublic.yml)}
  RoutePublic: ${file(./config/resources/network/RoutePublic.yml)}
  RouteTableAssociationSubnetA: ${file(./config/resources/network/RouteTableAssociationSubnetA.yml)}
  RouteTableAssociationSubnetB: ${file(./config/resources/network/RouteTableAssociationSubnetB.yml)}
  RouteTableAssociationSubnetC: ${file(./config/resources/network/RouteTableAssociationSubnetC.yml)}

  # RDS
  AuroraRDSClusterParameter: ${file(./config/resources/db/AuroraRDSClusterParameter.yml)}
  AuroraRDSInstanceParameter: ${file(./config/resources/db/AuroraRDSInstanceParameter.yml)}

  # SNS Topic
  SNSTopicBookingCreated: ${file(./config/resources/sns/SNSTopicBookingCreated.yml)}

Outputs:
  ServerlessSecurityGroup:
    Description: "Serverless Security Group"
    Value: !Ref ServerlessSecurityGroup
    Export:
      Name: ExportedServerlessSecurityGroup
  ServerlessSubnetGroup:
    Description: "Serverless Subnet Group"
    Value: !Ref ServerlessSubnetGroup
    Export:
      Name: ExportedServerlessSubnetGroup
  ServerlessVPCGA:
    Description: "Serverless VPCGA"
    Value: !Ref ServerlessVPCGA
    Export:
      Name: ExportedServerlessVPCGA
  AuroraRDSInstanceParameter:
    Description: "Aurora RDS Instance Parameter"
    Value: !Ref AuroraRDSInstanceParameter
    Export:
      Name: ExportedAuroraRDSInstanceParameter
  AuroraRDSClusterParameter:
    Description: "Aurora RDS Cluster Parameter"
    Value: !Ref AuroraRDSClusterParameter
    Export:
      Name: ExportedAuroraRDSClusterParameter
