service: rental-storage-infrastructure
frameworkVersion: "3"

plugins:
  - serverless-export-outputs
  - serverless-deployment-bucket

provider:
  name: aws
  region: us-east-1
  stage: dev
  deploymentBucket:
    name: rental-storage-infrastructure-resources

custom:
  namespace: rental-storage

resources:
  Resources:
    # Infrastructure
    ServerlessInternetGateway: ${file(./aws/resources/network/ServerlessInternetGateway.yml)}
    ServerlessVPC: ${file(./aws/resources/network/ServerlessVPC.yml)}
    ServerlessVPCGA: ${file(./aws/resources/network/ServerlessVPCGA.yml)}
    ServerlessSubnetA: ${file(./aws/resources/network/ServerlessSubnetA.yml)}
    ServerlessSubnetB: ${file(./aws/resources/network/ServerlessSubnetB.yml)}
    ServerlessSubnetC: ${file(./aws/resources/network/ServerlessSubnetC.yml)}
    ServerlessSubnetGroup: ${file(./aws/resources/network/ServerlessSubnetGroup.yml)}
    ServerlessSecurityGroup: ${file(./aws/resources/network/ServerlessSecurityGroup.yml)}
    RouteTablePublic: ${file(./aws/resources/network/RouteTablePublic.yml)}
    RoutePublic: ${file(./aws/resources/network/RoutePublic.yml)}
    RouteTableAssociationSubnetA: ${file(./aws/resources/network/RouteTableAssociationSubnetA.yml)}
    RouteTableAssociationSubnetB: ${file(./aws/resources/network/RouteTableAssociationSubnetB.yml)}
    RouteTableAssociationSubnetC: ${file(./aws/resources/network/RouteTableAssociationSubnetC.yml)}

    # S3
    ListingProfileS3Bucket: ${file(./aws/resources/s3/ListingProfileBucket.yml)}

    # RDS
    AuroraRDSClusterParameter: ${file(./aws/resources/rds/AuroraRDSClusterParameter.yml)}
    AuroraRDSInstanceParameter: ${file(./aws/resources/rds/AuroraRDSInstanceParameter.yml)}

    # SNS Topic
    SNSTopicBookingCreated: ${file(./aws/resources/sns/topic/booking/SNSTopicBookingCreated.yml)}

    # SQS
    UserSNSSubscriptionBookingCreated: ${file(./aws/resources/sqs/user/SNSSubscriptionBookingCreated.yml)}
    UserSQSQueue: ${file(./aws/resources/sqs/user/SQSQueue.yml)}
    UserSQSQueuePolicy: ${file(./aws/resources/sqs/user/SQSQueuePolicy.yml)}
    ListingSNSSubscriptionBookingCreated: ${file(./aws/resources/sqs/listing/SNSSubscriptionBookingCreated.yml)}
    ListingSQSQueue: ${file(./aws/resources/sqs/listing/SQSQueue.yml)}
    ListingSQSQueuePolicy: ${file(./aws/resources/sqs/listing/SQSQueuePolicy.yml)}

  Outputs:
    ServerlessSecurityGroup:
      Description: "Serverless Security Group"
      Value: !Ref ServerlessSecurityGroup
      Export:
        Name: ExportedServerlessSecurityGroup
    ServerlessSubnetGroup:
      Description: "Serverless Subnet Group"
      Value: !Ref ServerlessSubnetGroup
      Export:
        Name: ExportedServerlessSubnetGroup
    ServerlessVPCGA:
      Description: "Serverless VPCGA"
      Value: !Ref ServerlessVPCGA
      Export:
        Name: ExportedServerlessVPCGA
    AuroraRDSInstanceParameter:
      Description: "Aurora RDS Instance Parameter"
      Value: !Ref AuroraRDSInstanceParameter
      Export:
        Name: ExportedAuroraRDSInstanceParameter
    AuroraRDSClusterParameter:
      Description: "Aurora RDS Cluster Parameter"
      Value: !Ref AuroraRDSClusterParameter
      Export:
        Name: ExportedAuroraRDSClusterParameter
