service: rental-a-locker-infrastructure
variablesResolutionMode: 20210326

useDotenv: true
plugins:
  - serverless-deployment-bucket

provider:
  name: aws
  region: us-east-1
  stage: ${opt:stage, 'local'}
  deploymentBucket:
    name: ${self:provider.stage}-${aws:accountId}-rental-a-locker-infrastructure-resources

custom:
  namespace: app
  USER_DB_NAME: users
  USER_DB_USERNAME: master
  USER_DB_PASSWORD: password
  LISTING_DB_NAME: listings
  LISTING_DB_USERNAME: master
  LISTING_DB_PASSWORD: password
  BOOKING_TABLE_NAME: bookings

resources:
  Resources:
    # Infrastructure
    DBSubnetGroupServerless: ${file(./aws/resources/ec2/DBSubnetGroupServerless.yml)}
    InternetGateway: ${file(./aws/resources/ec2/InternetGateway.yml)}
    RoutePublic: ${file(./aws/resources/ec2/RoutePublic.yml)}
    RouteTablePublic: ${file(./aws/resources/ec2/RouteTablePublic.yml)}
    SecurityGroupServerless: ${file(./aws/resources/ec2/SecurityGroupServerless.yml)}
    SubnetA: ${file(./aws/resources/ec2/SubnetA.yml)}
    SubnetB: ${file(./aws/resources/ec2/SubnetB.yml)}
    SubnetC: ${file(./aws/resources/ec2/SubnetC.yml)}
    SubnetRouteTableAssociationA: ${file(./aws/resources/ec2/SubnetRouteTableAssociationA.yml)}
    SubnetRouteTableAssociationB: ${file(./aws/resources/ec2/SubnetRouteTableAssociationB.yml)}
    SubnetRouteTableAssociationC: ${file(./aws/resources/ec2/SubnetRouteTableAssociationC.yml)}
    VPC: ${file(./aws/resources/ec2/VPC.yml)}
    VPCGatewayAttachment: ${file(./aws/resources/ec2/VPCGatewayAttachment.yml)}

    # S3
    ListingProfileS3Bucket: ${file(./aws/resources/s3/ListingProfile/Bucket.yml)}
    BucketPolicyListingProfile: ${file(./aws/resources/s3/ListingProfile/BucketPolicy.yml)}

    # RDS
    UserRDSInstance: ${file(./aws/resources/rds/user/DBInstance.yml)}
    ListingRDSInstance: ${file(./aws/resources/rds/listing/DBInstance.yml)}

    # DynamoDBTable
    BookingDynamoDBTable: ${file(./aws/resources/dynamodb/Booking/Table.yml)}

    # SNS Topic
    TopicAuthentication: ${file(./aws/resources/sns/topic/TopicAuthentication.yml)}
    TopicBooking: ${file(./aws/resources/sns/topic/TopicBooking.yml)}
    TopicListing: ${file(./aws/resources/sns/topic/TopicListing.yml)}
    TopicPayment: ${file(./aws/resources/sns/topic/TopicPayment.yml)}
    TopicUser: ${file(./aws/resources/sns/topic/TopicUser.yml)}

    # SQS
    ## Booking
    QueueBooking: ${file(./aws/resources/sqs/booking/Queue.yml)}
    QueuePolicyBooking: ${file(./aws/resources/sqs/booking/QueuePolicy.yml)}
    DLQueueBooking: ${file(./aws/resources/sqs/booking/DLQueue.yml)}
    SubscriptionBookingUser: ${file(./aws/resources/sqs/booking/subscription/SubscriptionUser.yml)}

    # Kinesis
    KinesisStream: ${file(./aws/resources/kinesis/Stream.yml)}

    # IAM
    RoleLambda: ${file(./aws/resources/iam/RoleLambda.yml)}
  Outputs: ${file(./aws/outputs.yml)}
