service: rental-storage-infrastructure
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-export-outputs
  - serverless-deployment-bucket

provider:
  name: aws
  region: us-east-1
  stage: dev
  deploymentBucket:
    name: rental-storage-infrastructure-resources

custom:
  namespace: rental-storage
  USER_DB_NAME: user
  USER_DB_USERNAME: master
  USER_DB_PASSWORD: password
  ITEM_DB_NAME: item
  ITEM_DB_USERNAME: master
  ITEM_DB_PASSWORD: password
  LISTING_DB_NAME: listing
  LISTING_DB_USERNAME: master
  LISTING_DB_PASSWORD: password
  BOOKING_TABLE_NAME: booking

resources:
  Resources:
    ApiGateway: ${file(./aws/resources/apigateway.yml)}

    # Infrastructure
    ServerlessInternetGateway: ${file(./aws/resources/network/ServerlessInternetGateway.yml)}
    ServerlessVPC: ${file(./aws/resources/network/ServerlessVPC.yml)}
    ServerlessVPCGA: ${file(./aws/resources/network/ServerlessVPCGA.yml)}
    ServerlessSubnetA: ${file(./aws/resources/network/ServerlessSubnetA.yml)}
    ServerlessSubnetB: ${file(./aws/resources/network/ServerlessSubnetB.yml)}
    ServerlessSubnetC: ${file(./aws/resources/network/ServerlessSubnetC.yml)}
    ServerlessSubnetGroup: ${file(./aws/resources/network/ServerlessSubnetGroup.yml)}
    ServerlessSecurityGroup: ${file(./aws/resources/network/ServerlessSecurityGroup.yml)}
    RouteTablePublic: ${file(./aws/resources/network/RouteTablePublic.yml)}
    RoutePublic: ${file(./aws/resources/network/RoutePublic.yml)}
    RouteTableAssociationSubnetA: ${file(./aws/resources/network/RouteTableAssociationSubnetA.yml)}
    RouteTableAssociationSubnetB: ${file(./aws/resources/network/RouteTableAssociationSubnetB.yml)}
    RouteTableAssociationSubnetC: ${file(./aws/resources/network/RouteTableAssociationSubnetC.yml)}

    # S3
    ListingProfileS3Bucket: ${file(./aws/resources/s3/ListingProfileBucket.yml)}

    # RDS
    RDSClusterParameter: ${file(./aws/resources/rds/RDSClusterParameter.yml)}
    RDSInstanceParameter: ${file(./aws/resources/rds/RDSInstanceParameter.yml)}
    UserRDSCluster: ${file(./aws/resources/rds/user/RDSCluster.yml)}
    UserRDSInstance: ${file(./aws/resources/rds/user/RDSInstance.yml)}
    ListingRDSCluster: ${file(./aws/resources/rds/listing/RDSCluster.yml)}
    ListingRDSInstance: ${file(./aws/resources/rds/listing/RDSInstance.yml)}
    ItemRDSCluster: ${file(./aws/resources/rds/item/RDSCluster.yml)}
    ItemRDSInstance: ${file(./aws/resources/rds/item/RDSInstance.yml)}

    # DynamoDBTable
    BookingDynamoDBTable: ${file(./aws/resources/dynamodb/BookingTable.yml)}

    # SNS Topic
    SNSTopicItemCreated: ${file(./aws/resources/sns/topic/item/SNSTopicItemSaved.yml)}

    # SQS
    UserSNSSubscriptionItemSaved: ${file(./aws/resources/sqs/user/SNSSubscriptionItemSaved.yml)}
    UserSQSQueue: ${file(./aws/resources/sqs/user/SQSQueue.yml)}
    UserSQSQueuePolicy: ${file(./aws/resources/sqs/user/SQSQueuePolicy.yml)}
    ListingSNSSubscriptionItemSaved: ${file(./aws/resources/sqs/listing/SNSSubscriptionItemSaved.yml)}
    ListingSQSQueue: ${file(./aws/resources/sqs/listing/SQSQueue.yml)}
    ListingSQSQueuePolicy: ${file(./aws/resources/sqs/listing/SQSQueuePolicy.yml)}

    # IAM
    LambdaRole: ${file(./aws/resources/iam/LambdaRole.yml)}
  Outputs: ${file(./aws/outputs.yml)}
