service: rental-storage-infrastructure
frameworkVersion: "3"

plugins:
  - serverless-export-outputs

provider:
  name: aws
  region: us-east-1
  stage: dev

custom:
  namespace: rental-storage

resources:
  Resources:
    # Infrastructure
    ServerlessInternetGateway: ${file(./aws/resources/network/ServerlessInternetGateway.yml)}
    ServerlessVPC: ${file(./aws/resources/network/ServerlessVPC.yml)}
    ServerlessVPCGA: ${file(./aws/resources/network/ServerlessVPCGA.yml)}
    ServerlessSubnetA: ${file(./aws/resources/network/ServerlessSubnetA.yml)}
    ServerlessSubnetB: ${file(./aws/resources/network/ServerlessSubnetB.yml)}
    ServerlessSubnetC: ${file(./aws/resources/network/ServerlessSubnetC.yml)}
    ServerlessSubnetGroup: ${file(./aws/resources/network/ServerlessSubnetGroup.yml)}
    ServerlessSecurityGroup: ${file(./aws/resources/network/ServerlessSecurityGroup.yml)}
    RouteTablePublic: ${file(./aws/resources/network/RouteTablePublic.yml)}
    RoutePublic: ${file(./aws/resources/network/RoutePublic.yml)}
    RouteTableAssociationSubnetA: ${file(./aws/resources/network/RouteTableAssociationSubnetA.yml)}
    RouteTableAssociationSubnetB: ${file(./aws/resources/network/RouteTableAssociationSubnetB.yml)}
    RouteTableAssociationSubnetC: ${file(./aws/resources/network/RouteTableAssociationSubnetC.yml)}

    # RDS
    AuroraRDSClusterParameter: ${file(./aws/resources/rds/AuroraRDSClusterParameter.yml)}
    AuroraRDSInstanceParameter: ${file(./aws/resources/rds/AuroraRDSInstanceParameter.yml)}

    # SNS Topic
    SNSTopicBookingCreated: ${file(./aws/resources/sns/topic/booking/SNSTopicBookingCreated.yml)}

  Outputs:
    ServerlessSecurityGroup:
      Description: "Serverless Security Group"
      Value: !Ref ServerlessSecurityGroup
      Export:
        Name: ExportedServerlessSecurityGroup
    ServerlessSubnetGroup:
      Description: "Serverless Subnet Group"
      Value: !Ref ServerlessSubnetGroup
      Export:
        Name: ExportedServerlessSubnetGroup
    ServerlessVPCGA:
      Description: "Serverless VPCGA"
      Value: !Ref ServerlessVPCGA
      Export:
        Name: ExportedServerlessVPCGA
    AuroraRDSInstanceParameter:
      Description: "Aurora RDS Instance Parameter"
      Value: !Ref AuroraRDSInstanceParameter
      Export:
        Name: ExportedAuroraRDSInstanceParameter
    AuroraRDSClusterParameter:
      Description: "Aurora RDS Cluster Parameter"
      Value: !Ref AuroraRDSClusterParameter
      Export:
        Name: ExportedAuroraRDSClusterParameter
