service: rental-a-locker-infrastructure
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-export-outputs
  - serverless-deployment-bucket

provider:
  name: aws
  region: us-east-1
  stage: dev
  deploymentBucket:
    name: rental-a-locker-infrastructure-resources

custom:
  namespace: rental-a-locker
  USER_DB_NAME: user
  USER_DB_USERNAME: master
  USER_DB_PASSWORD: password
  ITEM_DB_NAME: item
  ITEM_DB_USERNAME: master
  ITEM_DB_PASSWORD: password
  LISTING_DB_NAME: listing
  LISTING_DB_USERNAME: master
  LISTING_DB_PASSWORD: password
  BOOKING_TABLE_NAME: booking

resources:
  Resources:
    #ApiGateway
    ApiGatewayRestApi: ${file(./aws/resources/apigateway/RestApi.yml)}
    ApiGatewayAuthorizer: ${file(./aws/resources/apigateway/Authorizer.yml)}

    # Infrastructure
    InternetGateway: ${file(./aws/resources/ec2/InternetGateway.yml)}
    VPC: ${file(./aws/resources/ec2/VPC.yml)}
    VPCGatewayAttachment: ${file(./aws/resources/ec2/VPCGatewayAttachment.yml)}
    SubnetA: ${file(./aws/resources/ec2/SubnetA.yml)}
    SubnetB: ${file(./aws/resources/ec2/SubnetB.yml)}
    SubnetC: ${file(./aws/resources/ec2/SubnetC.yml)}
    DBSubnetGroupServerless: ${file(./aws/resources/ec2/DBSubnetGroupServerless.yml)}
    SecurityGroupServerless: ${file(./aws/resources/ec2/SecurityGroupServerless.yml)}
    RouteTablePublic: ${file(./aws/resources/ec2/RouteTablePublic.yml)}
    RoutePublic: ${file(./aws/resources/ec2/RoutePublic.yml)}
    SubnetRouteTableAssociationA: ${file(./aws/resources/ec2/SubnetRouteTableAssociationA.yml)}
    SubnetRouteTableAssociationB: ${file(./aws/resources/ec2/SubnetRouteTableAssociationB.yml)}
    SubnetRouteTableAssociationC: ${file(./aws/resources/ec2/SubnetRouteTableAssociationC.yml)}

    # S3
    ListingProfileS3Bucket: ${file(./aws/resources/s3/ListingProfile/Bucket.yml)}

    # RDS
    DBClusterParameterGroup: ${file(./aws/resources/rds/DBClusterParameterGroup.yml)}
    DBParameterGroup: ${file(./aws/resources/rds/DBParameterGroup.yml)}
    UserRDSCluster: ${file(./aws/resources/rds/user/RDSCluster.yml)}
    UserRDSInstance: ${file(./aws/resources/rds/user/RDSInstance.yml)}
    ListingRDSCluster: ${file(./aws/resources/rds/listing/RDSCluster.yml)}
    ListingRDSInstance: ${file(./aws/resources/rds/listing/RDSInstance.yml)}
    ItemRDSCluster: ${file(./aws/resources/rds/item/RDSCluster.yml)}
    ItemRDSInstance: ${file(./aws/resources/rds/item/RDSInstance.yml)}

    # DynamoDBTable
    BookingDynamoDBTable: ${file(./aws/resources/dynamodb/Booking/Table.yml)}

    # SNS Topic
    SNSTopicItemCreated: ${file(./aws/resources/sns/topic/item/SNSTopicItemSaved.yml)}

    # SQS
    UserSNSSubscriptionItemSaved: ${file(./aws/resources/sqs/user/ItemSaved/Subscription.yml)}
    UserSQSQueue: ${file(./aws/resources/sqs/user/Queue.yml)}
    UserSQSDLQueue: ${file(./aws/resources/sqs/user/DLQueue.yml)}
    UserSQSQueuePolicy: ${file(./aws/resources/sqs/user/QueuePolicy.yml)}

    ListingSNSSubscriptionItemSaved: ${file(./aws/resources/sqs/listing/ItemSaved/Subscription.yml)}
    ListingSQSQueue: ${file(./aws/resources/sqs/listing/Queue.yml)}
    ListingSQSDLQueue: ${file(./aws/resources/sqs/listing/DLQueue.yml)}
    ListingSQSQueuePolicy: ${file(./aws/resources/sqs/listing/QueuePolicy.yml)}

    # IAM
    RoleLambda: ${file(./aws/resources/iam/RoleLambda.yml)}
  Outputs: ${file(./aws/outputs.yml)}
