service: rental-a-locker-infrastructure
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-export-outputs
  - serverless-deployment-bucket

provider:
  name: aws
  region: us-east-1
  stage: dev
  deploymentBucket:
    name: rental-a-locker-infrastructure-resources

custom:
  namespace: rental-a-locker
  USER_DB_NAME: users
  USER_DB_USERNAME: master
  USER_DB_PASSWORD: password
  LISTING_DB_NAME: listings
  LISTING_DB_USERNAME: master
  LISTING_DB_PASSWORD: password
  BOOKING_TABLE_NAME: bookings

resources:
  Resources:
    #ApiGateway
    ApiGatewayRestApi: ${file(./aws/resources/apigateway/RestApi.yml)}

    # Infrastructure
    DBSubnetGroupServerless: ${file(./aws/resources/ec2/DBSubnetGroupServerless.yml)}
    InternetGateway: ${file(./aws/resources/ec2/InternetGateway.yml)}
    RoutePublic: ${file(./aws/resources/ec2/RoutePublic.yml)}
    RouteTablePublic: ${file(./aws/resources/ec2/RouteTablePublic.yml)}
    SecurityGroupServerless: ${file(./aws/resources/ec2/SecurityGroupServerless.yml)}
    SubnetA: ${file(./aws/resources/ec2/SubnetA.yml)}
    SubnetB: ${file(./aws/resources/ec2/SubnetB.yml)}
    SubnetC: ${file(./aws/resources/ec2/SubnetC.yml)}
    SubnetRouteTableAssociationA: ${file(./aws/resources/ec2/SubnetRouteTableAssociationA.yml)}
    SubnetRouteTableAssociationB: ${file(./aws/resources/ec2/SubnetRouteTableAssociationB.yml)}
    SubnetRouteTableAssociationC: ${file(./aws/resources/ec2/SubnetRouteTableAssociationC.yml)}
    VPC: ${file(./aws/resources/ec2/VPC.yml)}
    VPCGatewayAttachment: ${file(./aws/resources/ec2/VPCGatewayAttachment.yml)}

    # S3
    ListingProfileS3Bucket: ${file(./aws/resources/s3/ListingProfile/Bucket.yml)}

    # RDS
    UserRDSInstance: ${file(./aws/resources/rds/user/DBInstance.yml)}
    ListingRDSInstance: ${file(./aws/resources/rds/listing/DBInstance.yml)}

    # DynamoDBTable
    BookingDynamoDBTable: ${file(./aws/resources/dynamodb/Booking/Table.yml)}

    # SNS Topic
    TopicUser: ${file(./aws/resources/sns/topic/TopicUser.yml)}

    # SQS
    SlackQueue: ${file(./aws/resources/sqs/slack/Queue.yml)}
    SlackDLQueue: ${file(./aws/resources/sqs/slack/DLQueue.yml)}
    SlackQueuePolicy: ${file(./aws/resources/sqs/slack/QueuePolicy.yml)}
    SlackSubscriptionUser: ${file(./aws/resources/sqs/slack/subscription/SubscriptionUser.yml)}

    # IAM
    RoleLambda: ${file(./aws/resources/iam/RoleLambda.yml)}
  Outputs: ${file(./aws/outputs.yml)}
