service: composition
frameworkVersion: "3"

plugins:
  - serverless-deployment-bucket
  - serverless-export-env

provider:
  name: aws
  runtime: nodejs18.x
  stage: local
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-${aws:accountId}-sls-composition
  iam:
    role: ${ssm:/terraform/iam/lambda-role-arn}
  apiGateway:
    restApiId: ${ssm:/terraform/apigateway/rest-api-id}
    restApiRootResourceId: ${ssm:/terraform/apigateway/rest-api-root-resource-id}
  ecr:
    images:
      app:
        path: ./
        file: Dockerfile
        buildArgs:
  environment:
    SERVICE_API_ENDPOINT: ${self:custom.SERVICE_API_ENDPOINT}
    ACCOUNT_ID: ${aws:accountId}

custom:
  namespace: app
  service: composition
  SERVICE_API_ENDPOINT:
    Fn::Join:
      - ""
      - - "https://"
        - ${self:provider.apiGateway.restApiId}
        - ".execute-api."
        - ${self:provider.region}
        - ".amazonaws.com/"
        - ${self:provider.stage}
  export-env:
    filename: .env
    overwrite: true

functions:
  - ${file(./aws/functions/query.yml)}
  - ${file(./aws/functions/mutation.yml)}
