- type: AWS_LAMBDA
  name: createTodoFunction
  config:
    functionName: createTodo

- type: AWS_LAMBDA
  name: updateTodoFunction
  config:
    functionName: updateTodo

- type: AWS_LAMBDA
  name: deleteTodoFunction
  config:
    functionName: deleteTodo

- type: AWS_LAMBDA
  name: getTodosFunction
  config:
    functionName: getTodos

- type: AWS_LAMBDA
  name: getUserFunction
  config:
    functionName: getUser

- type: AWS_LAMBDA
  name: createUserFunction
  config:
    functionName: createUser
