NAMESPACE = @appsync

.PHONY: set-profile
set-profile:
	@echo "Setting AWS_PROFILE to rental-storage"
	@export AWS_PROFILE=rental-storage

clean:
	@echo "[ $(NAMESPACE) ]Cleaning up node_modules and package-lock.json"
	@rm -rf package-lock.json node_modules

