service: infrastructure-appsync
variablesResolutionMode: 20210326

plugins:
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies
  - serverless-appsync-plugin
  - serverless-pseudo-parameters
  - serverless-deployment-bucket

provider:
  name: aws
  stage: local
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-${aws:accountId}-sls-infrastructure-appsync

custom:
  namespace: app
  service: api-appsync
  appSync:
    - name: ${self:custom.namespace}-private-${self:custom.service}
      authenticationType: AWS_LAMBDA
      lambdaAuthorizerConfig:
        lambdaFunctionArn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:provider.stage}-${self:custom.namespace}-authorizer
        authorizerResultTtlInSeconds: 0
      schema:
        - schema/common.graphql
        - schema/private/*.graphql
      mappingTemplatesLocation: ./aws/appsync/mapping-templates/private
      dataSources:
        - ${file(./aws/appsync/data-sources/booking.yml)}
        - ${file(./aws/appsync/data-sources/image.yml)}
        - ${file(./aws/appsync/data-sources/space.yml)}
        - ${file(./aws/appsync/data-sources/user.yml)}
      mappingTemplates:
        - ${file(./aws/appsync/mapping-templates/private/booking/mapping-template.yml)}
        - ${file(./aws/appsync/mapping-templates/private/image/mapping-template.yml)}
        - ${file(./aws/appsync/mapping-templates/private/space/mapping-template.yml)}
        - ${file(./aws/appsync/mapping-templates/private/user/mapping-template.yml)}

    - name: ${self:custom.namespace}-public-${self:custom.service}
      authenticationType: API_KEY
      schema:
        - schema/common.graphql
        - schema/public/*.graphql
      mappingTemplatesLocation: ./aws/appsync/mapping-templates/public
      dataSources:
        - ${file(./aws/appsync/data-sources/booking.yml)}
        - ${file(./aws/appsync/data-sources/image.yml)}
        - ${file(./aws/appsync/data-sources/space.yml)}
        - ${file(./aws/appsync/data-sources/user.yml)}
      mappingTemplates:
        - ${file(./aws/appsync/mapping-templates/public/space/mapping-template.yml)}
