service: infrastructure-appsync
variablesResolutionMode: 20210326

plugins:
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies
  - serverless-appsync-plugin
  - serverless-pseudo-parameters
  - serverless-deployment-bucket

provider:
  name: aws
  stage: local
  region: us-east-1
  deploymentBucket:
    name: ${self:provider.stage}-${aws:accountId}-sls-infrastructure-appsync

custom:
  namespace: app
  service: infrastructure-appsync
  appSync:
    name: ${self:custom.namespace}-${self:custom.service}
    authenticationType: AWS_LAMBDA
    lambdaAuthorizerConfig:
      lambdaFunctionArn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:provider.stage}-${self:custom.namespace}-authorizer
      authorizerResultTtlInSeconds: 0
    schema:
      - schema/booking.graphql
      - schema/image.graphql
      - schema/listing.graphql
      - schema/user.graphql
      - schema/payment.graphql
    mappingTemplatesLocation: ./aws/appsync/mapping-templates
    dataSources:
      - ${file(./aws/appsync/data-sources/booking.yml)}
      - ${file(./aws/appsync/data-sources/image.yml)}
      - ${file(./aws/appsync/data-sources/listing.yml)}
      - ${file(./aws/appsync/data-sources/user.yml)}
      - ${file(./aws/appsync/data-sources/payment.yml)}
    mappingTemplates:
      - ${file(./aws/appsync/mapping-templates/booking/mapping-template.yml)}
      - ${file(./aws/appsync/mapping-templates/image/mapping-template.yml)}
      - ${file(./aws/appsync/mapping-templates/listing/mapping-template.yml)}
      - ${file(./aws/appsync/mapping-templates/user/mapping-template.yml)}
      - ${file(./aws/appsync/mapping-templates/payment/mapping-template.yml)}
