name: Build and Test Typescript

runs:
  using: "composite"
  steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: "npm"

    - name: Install packages
      run: make install-deps
      shell: bash

    - name: Cache node modules
      id: node-modules-cache
      uses: actions/cache@v3
      with:
        path: "**/node_modules"
        key: node-modules-cache

    - name: Build
      run: npm run build
      shell: bash

    - name: Cache dist modules
      id: dist-cache
      uses: actions/cache@v3
      with:
        path: "**/dist/**"
        key: dist-cache
