# User
## Query
- type: AWS_LAMBDA
  name: findGuestByIdFunction
  config:
    lambdaFunctionArn: arn:aws:lambda:${self:provider.region}:474489807730:function:${self:custom.service}-user-${self:provider.stage}-findGuestById
    serviceRoleArn: arn:aws:iam::474489807730:role/${self:custom.service}-user-${self:provider.stage}-${self:provider.region}-lambdaRole

- type: AWS_LAMBDA
  name: findHostByIdFunction
  config:
    lambdaFunctionArn: arn:aws:lambda:${self:provider.region}:474489807730:function:${self:custom.service}-user-${self:provider.stage}-findHostById
    serviceRoleArn: arn:aws:iam::474489807730:role/${self:custom.service}-user-${self:provider.stage}-${self:provider.region}-lambdaRole

## Mutation
- type: AWS_LAMBDA
  name: registerGuestFunction
  config:
    lambdaFunctionArn: arn:aws:lambda:us-east-1:474489807730:function:rental-storage-user-dev-registerGuest
    serviceRoleArn: arn:aws:iam::474489807730:role/rental-storage-user-dev-us-east-1-lambdaRole

- type: AWS_LAMBDA
  name: removeGuestByIdFunction
  config:
    lambdaFunctionArn: arn:aws:lambda:${self:provider.region}:474489807730:function:${self:custom.service}-user-${self:provider.stage}-removeGuestById
    serviceRoleArn: arn:aws:iam::474489807730:role/${self:custom.service}-user-${self:provider.stage}-${self:provider.region}-lambdaRole

- type: AWS_LAMBDA
  name: registerHostFunction
  config:
    lambdaFunctionArn: arn:aws:lambda:${self:provider.region}:474489807730:function:${self:custom.service}-user-${self:provider.stage}-registerHost
    serviceRoleArn: arn:aws:iam::474489807730:role/${self:custom.service}-user-${self:provider.stage}-${self:provider.region}-lambdaRole

- type: AWS_LAMBDA
  name: removeHostByIdFunction
  config:
    lambdaFunctionArn: arn:aws:lambda:${self:provider.region}:474489807730:function:${self:custom.service}-user-${self:provider.stage}-removeHostById
    serviceRoleArn: arn:aws:iam::474489807730:role/${self:custom.service}-user-${self:provider.stage}-${self:provider.region}-lambdaRole

# Listing
## Query
- type: AWS_LAMBDA
  name: findListingByIdFunction
  config:
    lambdaFunctionArn: arn:aws:lambda:${self:provider.region}:474489807730:function:${self:custom.service}-listing-${self:provider.stage}-findListingById
    serviceRoleArn: arn:aws:iam::474489807730:role/${self:custom.service}-listing-${self:provider.stage}-${self:provider.region}-lambdaRole

- type: AWS_LAMBDA
  name: findListingsWithinLatLngFunction
  config:
    lambdaFunctionArn: arn:aws:lambda:${self:provider.region}:474489807730:function:${self:custom.service}-listing-${self:provider.stage}-findListingsWithinLatLng
    serviceRoleArn: arn:aws:iam::474489807730:role/${self:custom.service}-listing-${self:provider.stage}-${self:provider.region}-lambdaRole

## Mutation
- type: AWS_LAMBDA
  name: addListingFunction
  config:
    lambdaFunctionArn: arn:aws:lambda:${self:provider.region}:474489807730:function:${self:custom.service}-listing-${self:provider.stage}-addListing
    serviceRoleArn: arn:aws:iam::474489807730:role/${self:custom.service}-listing-${self:provider.stage}-${self:provider.region}-lambdaRole

- type: AWS_LAMBDA
  name: removeListingByIdFunction
  config:
    lambdaFunctionArn: arn:aws:lambda:${self:provider.region}:474489807730:function:${self:custom.service}-listing-${self:provider.stage}-removeListingById
    serviceRoleArn: arn:aws:iam::474489807730:role/${self:custom.service}-listing-${self:provider.stage}-${self:provider.region}-lambdaRole
