service: service-payment
variablesResolutionMode: 20210326

plugins:
  - serverless-deployment-bucket
  - serverless-export-env

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, 'local'}
  region: us-east-1
  lambdaHashingVersion: 20201221
  deploymentBucket:
    name: ${self:provider.stage}-${aws:accountId}-payment-resources
  iam:
    role: !ImportValue ExportedRoleLambdaArn
  apiGateway:
    restApiId: !ImportValue ApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ApiGatewayRootResourceId
  ecr:
    images:
      app:
        path: ./
  environment:
    SERVICE_API_ENDPOINT: ${self:custom.SERVICE_API_ENDPOINT}
    STAGE: ${self:provider.stage}
    ACCOUNT_ID: ${aws:accountId}
    DB_HOST: ${self:custom.DB_HOST}
    DB_NAME: ${self:custom.DB_NAME}
    DB_USERNAME: ${self:custom.DB_USERNAME}
    DB_PASSWORD: ${self:custom.DB_PASSWORD}
    DB_PORT: ${self:custom.DB_PORT}

custom:
  namespace: app
  service: payment
  DB_HOST: !ImportValue ExportedPaymentRDSDBHost
  DB_NAME: !ImportValue ExportedPaymentRDSDBName
  DB_USERNAME: !ImportValue ExportedPaymentRDSDBUsername
  DB_PASSWORD: !ImportValue ExportedPaymentRDSDBPassword
  DB_PORT: !ImportValue ExportedPaymentRDSDBPort
  SERVICE_API_ENDPOINT:
    Fn::Join:
      - ""
      - - "https://"
        - ${self:provider.apiGateway.restApiId}
        - ".execute-api."
        - ${self:provider.region}
        - ".amazonaws.com/"
        - ${self:provider.stage}

  export-env:
    filename: .env
    overwrite: true

functions:
  - ${file(./aws/functions/apigateway.yml)}
