- type: Query
  field: getUser
  dataSource: getUserFunction
  request: false
  response: false
- type: Mutation
  field: createUser
  dataSource: createUserFunction
  request: false
  response: false
