service: rental-storage-api
frameworkVersion: "3"

useDotenv: true

plugins:
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies
  - serverless-appsync-plugin
  - serverless-pseudo-parameters

provider:
  name: aws
  stage: dev
  region: us-east-1

custom:
  namespace: rental-storage
  service: api
  appSync:
    name: ${self:custom.namespace}-${self:custom.service}
    authenticationType: API_KEY
    mappingTemplates: ${file(./aws/appsync/mapping-templates.yml)}
    dataSources: ${file(./aws/appsync/data-sources.yml)}
