service: rental-storage-api
frameworkVersion: "3"

plugins:
  - serverless-plugin-common-excludes # this should go before serverless-plugin-include-dependencies
  - serverless-plugin-include-dependencies
  - serverless-appsync-plugin
  - serverless-pseudo-parameters
  - serverless-deployment-bucket

provider:
  name: aws
  stage: dev
  region: us-east-1
  deploymentBucket:
    name: rental-storage-api-resources

custom:
  namespace: rental-storage
  service: api
  appSync:
    name: ${self:custom.namespace}-${self:custom.service}
    authenticationType: AWS_LAMBDA
    lambdaAuthorizerConfig:
      lambdaFunctionArn: arn:aws:lambda:${aws:region}:${aws:accountId}:function:${self:custom.namespace}-authorizer-${self:provider.stage}-Authorizer

    schema:
      - schema/booking.graphql
      - schema/image.graphql
      - schema/listing.graphql
      - schema/user.graphql
    dataSources:
      - ${file(./aws/appsync/data-sources/booking.yml)}
      - ${file(./aws/appsync/data-sources/image.yml)}
      - ${file(./aws/appsync/data-sources/listing.yml)}
      - ${file(./aws/appsync/data-sources/user.yml)}
    mappingTemplates:
      - ${file(./aws/appsync/mapping-templates/booking.yml)}
      - ${file(./aws/appsync/mapping-templates/image.yml)}
      - ${file(./aws/appsync/mapping-templates/listing.yml)}
      - ${file(./aws/appsync/mapping-templates/user.yml)}
