on: workflow_call

jobs:
  # unit-test-python:
  #   name: Python
  #   timeout-minutes: 15
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       package:
  #         - image
  #         - slack
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - uses: dorny/paths-filter@v2
  #       id: changes
  #       with:
  #         filters: |
  #           package:
  #             - 'packages/service-${{ matrix.package }}/**'

  unit-test-go:
    name: Go
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - user
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            package:
              - 'packages/service-${{ matrix.package }}/**'

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.13.1"
        if: steps.changes.outputs.package == 'true'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          profile-name: rental-storage

      - name: Run Docker-Compose
        run: |
          cd packages/service-${{ matrix.package }}
          make deps-start
        shell: bash
        if: steps.changes.outputs.package == 'true'

      - name: Test service
        run: |
          cd packages/service-${{ matrix.package }}
          make test-integration
        shell: bash
        if: steps.changes.outputs.package == 'true'

      - name: Cleanup
        run: |
          cd packages/service-${{ matrix.package }}
          make deps-stop
        shell: bash
        if: steps.changes.outputs.package == 'true'
