on: workflow_call

jobs:
  setup-composition:
    name: Composition Service
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check files changed
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2

      - name: Setup Typescript environment
        uses: ./.github/actions/setup-typescript
        with:
          package: composition

  setup-go:
    name: Go Service
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - authentication
          - authorizer
          - booking
          - space
          - user
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check files changed
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.0.2

      - name: Setup Go environment
        uses: ./.github/actions/setup-go
        with:
          package: service-${{ matrix.package }}
