name: Integration Test

on:
  workflow_call:

jobs:
  integration-test-typescript:
    name: Typescript
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: ./.github/actions/setup-nodejs

      - name: Run Test
        uses: ./.github/actions/integration-test-nodejs

  # unit-test-python:
  #   name: Unit Test (Python)
  #   timeout-minutes: 15
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Run Test
  #       uses: ./.github/actions/test-python

  # unit-test-golang:
  #   name: Unit Test (Go)
  #   timeout-minutes: 15
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Run Test
  #       uses: ./.github/actions/test-golang
