on:
  workflow_call:

jobs:
  setup:
    name: Setup environment
    timout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate env files
        run: npm run generate:env:dev
        shell: bash

  integration-test-typescript:
    name: Typescript
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Setup Typescript
      #   uses: ./.github/actions/setup-typescript

      - name: Run Test
        uses: ./.github/actions/integration-test-typescript
        with:
          environment: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

  integration-test-python:
    name: Python
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Test
        uses: ./.github/actions/integration-test-python
        with:
          environment: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

  integration-test-go:
    name: Go
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Retrieve cache
        uses: ./.github/actions/retrieve-cache

      - name: Run Test
        uses: ./.github/actions/integration-test-go
        with:
          environment: dev
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
