name: Develop Pipeline

on:
  push:
    branches: "dev"

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/setup.yml

  deploy:
    name: Deploy
    needs: [setup-typescript, setup-go]
    uses: ./.github/workflows/deploy-dev.yml
    secrets: inherit

  integration:
    name: Integration Test
    needs: [deploy]
    uses: ./.github/workflows/test-integration.yml
    secrets: inherit
