name: Destroy

on:
  workflow_dispatch:
  pull_request:

jobs:
  destory-serverless:
    name: Serverless
    uses: ./.github/workflows/call-destory-serverless.yml
  destroy-terraform:
    name: Terraform
    needs: [destroy-serverless]
    uses: ./.github/workflows/call-destroy-terraform.yml
