name: Develop Pipeline

on:
  push:
    branches: "dev"

jobs:
  deploy:
    name: Deploy
    environment: dev
    uses: ./.github/workflows/deploy-dev.yml
    secrets: inherit

  integration-test:
    name: Integration Test
    needs: [deploy]
    uses: ./.github/workflows/test-integration.yml
    secrets: inherit
