name: Develop Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["dev"]

jobs:
  setup-build:
    name: Setup
    uses: ./.github/workflows/call-setup-build.yml

  validate-terraform:
    name: Core Infrastructure
    uses: ./.github/workflows/call-validate-terraform.yml
    secrets: inherit

  deploy-serverless:
    name: Deploy Services
    needs: [setup-build, validate-terraform]
    uses: ./.github/workflows/call-deploy-serverless.yml
    secrets: inherit

  test-integration:
    name: Integration Test
    needs: [setup-build, validate-terraform, deploy-serverless]
    uses: ./.github/workflows/call-test-integration.yml
    secrets: inherit
