name: Develop Pipeline

on:
  push:
    branches: "dev"

jobs:
  setup-typescript:
    name: Setup / Typescript
    timeout-minutes: 15
    runs-on: ubuntu-latest
    matrix:
      - booking
      - listing
      - user
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Typescript
        uses: ./.github/actions/setup-typescript
        with:
          package: ${{ matrix.package }}

  setup-go:
    name: Setup / Go
    timeout-minutes: 15
    runs-on: ubuntu-latest
    matrix:
      - authentication
      - authorizer
      - payment
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: ./.github/actions/setup-go
        with:
          package: ${{ matrix.package }}

  deploy:
    name: Deploy
    needs: [setup-typescript, setup-go]
    uses: ./.github/workflows/deploy-dev.yml
    secrets: inherit

  integration:
    name: Integration Test
    needs: [deploy]
    uses: ./.github/workflows/test-integration.yml
    secrets: inherit
