name: Develop Pipeline

on:
  # push:
  #   branches: "dev"
  pull_request:

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/setup-deploy.yml

  deploy:
    name: Deploy
    needs: [setup]
    uses: ./.github/workflows/deploy-dev.yml
    secrets: inherit

  integration-test:
    name: Integration Test
    needs: [deploy]
    uses: ./.github/workflows/test-integration.yml
    secrets: inherit
