name: Develop Pipeline

on:
  # push:
  #   branches: "dev"
  pull_request:
    types: [opened, synchronize]

jobs:
  setup:
    name: Setup
    uses: ./.github/workflows/setup.yml

  deploy:
    name: Deploy (dev)
    needs: [setup]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install root dependencies
        run: npm install

      - name: Install deps
        run: make install-deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy / Develop
        run: make deploy-dev

  integration:
    name: Integration Test
    needs: [deploy]
    uses: ./.github/workflows/integration-test.yml
    secrets: inherit
