name: Develop Pipeline

on:
  # push:
  #   branches: "dev"
  pull_request:
    types: [opened, synchronize]

jobs:
  setup-deps:
    name: Dependency Install
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        uses: ./.github/actions/setup-deps

  deploy:
    name: Deploy (dev)
    needs: [setup-deps]
    runs-on: ubuntu-latest
    if: "!failure() && !cancelled()"
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install global packages
        run: npm install -g serverless

      - name: Setup dependencies
        uses: .github/actions/setup-deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy / Develop
        run: sls deploy --stage dev

  integration-tests:
    name: Integration Test
    needs: [deploy]
    runs-on: ubuntu-latest
    if: "!failure() && !cancelled()"
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dependencies
        uses: .github/actions/setup-deps

      - name: Run Test
        run: echo "Simulating Integration test"
