name: Develop Pipeline

on:
  # push:
  #   branches: "dev"
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    name: Deploy (dev)
    runs-on: ubuntu-latest
    needs: [unit-test-typescript, unit-test-python, unit-test-golang]
    if: "!failure() && !cancelled()"
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install global packages
        run: npm install -g serverless

      - name: Retreive node_modules cache
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: node-modules-cache

      - name: Install root dependencies
        run: npm install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        shell: bash

      - name: Install package dependencies
        run: make install-deps
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy / Develop
        run: sls deploy --stage dev
