name: PR Pipeline

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  label-by-branch:
    name: Add/Remove branch labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          configuration-path: .github/labeler.yml
          repo-token: "${{ secrets.GH_TOKEN }}"

  test-unit:
    name: Unit Test
    uses: ./.github/workflows/call-test-unit.yml

  check-terraform:
    name: Terraform
    uses: ./.github/workflows/call-terraform.yml
    secrets: inherit
