name: PR Pipeline (Feature)

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  label-by-branch:
    name: Add/Remove branch labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ffittschen/pr-branch-labeler@v1
        with:
          repo-token: "${{ secrets.GH_TOKEN }}"

  unit-test-typescript:
    name: Unit test typescript services
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Typescript packages
        uses: ./.github/actions/setup-nodejs

      - name: Unit Test Typescript packages
        uses: ./.github/actions/test-nodejs

  unit-test-python:
    name: Unit test python services
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test Python packages
        uses: ./.github/actions/test-python

  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    needs: [unit-test-typescript, unit-test-python]
    if: "!failure() && !cancelled()"
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install global packages
        run: npm install -g serverless

      - name: Retreive node_modules cache
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: node-modules-cache

      - name: Install root dependencies
        run: npm install
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        shell: bash

      - name: Install package dependencies
        run: make install-deps
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy
        run: sls deploy
