on:
  workflow_call:

jobs:
  setup-typescript:
    name: Typescript
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Typescript
        uses: ./.github/actions/setup-typescript

  setup-python:
    name: Python
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: ./.github/actions/setup-python

  setup-go:
    name: Go
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: ./.github/actions/setup-go
