on: workflow_call

jobs:
  setup-root:
    name: Root
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node_modules
        run: npm install
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: node-modules-${{ github.sha }}
          path: node_modules
          retention-days: 1

  setup-typescript:
    name: Typescript
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - booking
          - listing
          - user
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node_modules
        run: |
          cd packages/service-${{ matrix.package }}
          npm install
        shell: bash

      - name: Build
        run: |
          cd packages/service-${{ matrix.package }}
          npm run build
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: node-modules-${{ matrix.package }}-${{ github.sha }}
          path: packages/service-${{ matrix.package }}/node_modules
          retention-days: 1

      - uses: actions/upload-artifact@v3
        with:
          name: dist-${{ matrix.package }}-${{ github.sha }}
          path: packages/service-${{ matrix.package }}/dist
          retention-days: 1

  setup-go:
    name: Go
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - authentication
          - authorizer
          - payment
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build ${{ matrix.package }} service
        run: |
          cd packages/service-${{ matrix.package }}
          make build
        shell: bash

      - uses: actions/upload-artifact@v3
        with:
          name: bin-${{ matrix.package }}-${{ github.sha }}
          path: packages/service-${{ matrix.package }}/bin
          retention-days: 1
