on:
  workflow_call:

jobs:
  unit-test-typescript:
    name: Typescript
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - booking
          - listing
          - user
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            package:
              - '${{ matrix.package }}/**'

      - name: Setup
        uses: ./.github/actions/setup-typescript
        if: steps.changes.outputs.package == 'true'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "npm"
        if: steps.changes.outputs.package == 'true'

      - name: Retreive node_modules cache
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: node-modules-cache
        if: steps.changes.outputs.package == 'true'

      - name: Install dependencies
        run: make install-deps
        shell: bash
        if: steps.changes.outputs.package == 'true' && steps.node-modules-cache.outputs.cache-hit != 'true'

      - name: Retrieve dist cache
        id: dist-cache
        uses: actions/cache@v3
        with:
          path: "**/dist"
          key: dist-cache
        if: steps.changes.outputs.package == 'true'

      - name: Build package
        run: |
          cd package/service-${{ matrix.package }}
        shell: bash
        if: steps.changes.outputs.package == 'true' && steps.dist-cache.outputs.cache-hit != 'true'

      - name: Test ${{ matrix.package }} service
        run: |
          cd package/service-${{ matrix.package }}
          npm run test:unit
        shell: bash
        if: steps.changes.outputs.package == 'true'

  unit-test-python:
    name: Python
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - image
          - slack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            package:
              - '${{ matrix.package }}/**'

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
        if: steps.changes.outputs.package == 'true'

      - name: Install global dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
        shell: bash
        if: steps.changes.outputs.package == 'true'

      - name: Install Image service dependencies
        run: |
          cd packages/service-${{ matrix.package }}
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash
        if: steps.changes.outputs.package == 'true'

      - name: Test ${{ matrix.package }} Service
        run: |
          cd packages/service-${{ matrix.package }}
          make unit-test
        shell: bash
        if: steps.changes.outputs.package == 'true'

  unit-test-go:
    name: Go
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - authorizer
          - authentication
          - payment
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            package:
              - '${{ matrix.package }}/**'

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.13.1" # The Go version to download (if necessary) and use.
        if: steps.changes.outputs.package == 'true'

      - name: Test authorizer service
        run: |
          cd packages/service-${{ matrix.package }}
          make unit-test
        shell: bash
        if: steps.changes.outputs.package == 'true'
