on:
  workflow_call:

jobs:
  unit-test-typescript:
    name: Typescript
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-typescript

      - name: Run Test
        uses: ./.github/actions/unit-test-typescript

  unit-test-python:
    name: Python
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - image
          - slack
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install global dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
        shell: bash

      - name: Install Image service dependencies
        run: |
          cd packages/service-${{ matrix.package }}
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Test ${{ matrix.package }} Service
        run: |
          cd packages/service-${{ matrix.package }}
          make unit-test
        shell: bash

  unit-test-go:
    name: Go
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - authorizer
          - authentication
          - payment
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.13.1" # The Go version to download (if necessary) and use.

      - name: Test authorizer service
        run: |
          cd packages/service-${{ matrix.package }}
          make unit-test
        shell: bash
