name: Unit Test

on:
  workflow_call:

jobs:
  unit-test-typescript:
    name: Typescript
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-typescript

      - name: Run Test
        uses: ./.github/actions/unit-test-typescript

  unit-test-python:
    name: Python
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Test
        uses: ./.github/actions/unit-test-python

  unit-test-golang:
    name: Go
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Test
        uses: ./.github/actions/unit-test-golang
